import type { CultureStory } from '../stories';

export const HINDI_STORIES: Omit<CultureStory, 'id'>[] = [

  // 1
  {
    title: 'The Wise Turtle and the Lake',
    titleNative: 'बुद्धिमान कछुआ और झील',
    category: 'Panchatantra & Animals 🦊',
    emoji: '🐢',
    paragraphs: [
      { native: 'बहुत प्राचीन समय की बात है, दक्षिण भारत के घने जंगलों के बीच एक विशाल नीली झील हुआ करती थी। उस झील का पानी सुनहरी धूप में शीशे की तरह चमकता था। झील के किनारों पर हज़ारों कमल के फूल खिले रहते थे, जिनके रंग बहुत ही मनमोहक थे। झील में मछलियाँ, मेंढक और केकड़े खुशी-खुशी रहते थे। लेकिन सबसे प्रसिद्ध था वहाँ का कछुआ — बूढ़ा कम्बन। कम्बन सौ साल का हो चुका था। उसके खोल पर हरी काई जमी हुई थी। उसकी आँखों में गहराई भी थी और प्रेम व बुद्धि भी।', english: 'In very ancient times, in the midst of the dense forests of South India, there lay a great blue lake. The clear water of that lake always shimmered like a mirror under the golden sun. Along the shores of the lake, thousands of lotus flowers bloomed in radiant colours. Fish, frogs, and crabs lived happily in the lake. But most famous of all was the tortoise — the ancient one called Kamban. Kamban was one hundred years old. Green moss had grown over his shell. His eyes were deep and full of love and wisdom.' },
      { native: 'एक गर्मी के मौसम में बारिश ने आना बंद कर दिया। जलस्रोत सूखने लगे और अपना रास्ता खो बैठे। झील धीरे-धीरे सिकुड़ने लगी। मछलियाँ डर गईं। मेंढक काँपने लगे। जंगली जानवर पानी की तलाश में इधर-उधर भटकने लगे। उसी समय गोपी नाम का एक छोटा बंदर झील के किनारे बैठा फूट-फूट कर रो रहा था। "अब हम कहाँ जाएँगे? पानी के बिना हम जी नहीं पाएँगे," गोपी ने बिलखते हुए कहा। कम्बन ने यह सुना। वह धीरे-धीरे चलकर गोपी के पास आया।', english: 'One summer, the rains failed to arrive. Water sources began to dry up and lose their paths. The lake slowly began to shrink. The fish grew frightened. The frogs trembled with fear. Wild animals wandered desperately searching for water. At that moment, a young monkey named Gopi sat on the bank of the lake, weeping bitterly. "Where shall we go now? Without water we cannot survive," Gopi lamented. Kamban heard this. He walked slowly and came near Gopi.' },
      { native: '"बच्चे, रो मत," कम्बन ने बड़े प्रेम से कहा। "यह झील भले ही सूख जाए, पर पहाड़ पर एक झरना है। लेकिन उस झरने तक जाने का रास्ता बहुतों को नहीं पता। मैं अपनी जवानी में एक बार वहाँ गया था। रास्ता बहुत कठिन और खतरनाक है। पर अगर हममें साहस और एकता हो, तो हम ज़रूर वह झरना खोज निकालेंगे।" गोपी ने कम्बन की बातें सुनीं और अपना सिर ऊपर उठाया। उसकी आँखों के आँसू थम गए। धीरे-धीरे उसके मन में साहस एक नए बीज की तरह अंकुरित होने लगा।', english: '"Child, do not weep," said Kamban with great warmth and love. "Even if this lake dries up, there is a spring in the mountain. But the path to reach it is unknown to many. I traveled there once in my youth. The road is very difficult and treacherous. But if we have courage and unity together, we will certainly find that spring." Gopi raised his head when he heard Kamban\'s words. The tears in his eyes stopped flowing. Slowly, courage began to sprout in his heart like a new seed.' },
      { native: 'कम्बन ने झील में रहने वाले सारे जानवरों को इकट्ठा किया। मछलियाँ, मेंढक, पक्षी, बंदर, हिरण — सब एक जगह जमा हो गए। "हम सब मिलकर यात्रा करेंगे। कोई भी अकेला नहीं जाएगा। हम छोटे जानवरों की रक्षा करेंगे। बुज़ुर्गों की मदद करेंगे। एकता ही हमारी सबसे बड़ी ताकत है," कम्बन ने दृढ़ता से घोषणा की। सभी जानवरों ने एक होकर कम्बन को अपना नेता माना। यात्रा आशा भरे दिलों के साथ शुरू हुई।', english: 'Kamban gathered all the animals living in the lake together. Fish, frogs, birds, monkeys, deer — everyone assembled in one place. "Let us travel together. No one should go alone. We will protect the young animals. We will help the elders. Our unity is our greatest strength," announced Kamban firmly. All the animals united and accepted Kamban as their leader. The journey began with hopeful hearts.' },
      { native: 'यात्रा बेहद कठिन थी। वे पत्थरों और काँटों से भरे जंगली रास्तों पर चले। धूप कड़ी थी। पानी न होने से सब प्यास से तड़प रहे थे। एक छोटा मेंढक थककर गिर पड़ा। गोपी ने तुरंत उसे उठाकर अपनी पीठ पर बिठा लिया। एक बूढ़ा हिरण पैर के दर्द से लड़खड़ाने लगा। दो जवान बंदर हिरण के दोनों ओर खड़े होकर उसे सहारा देते हुए चले। कम्बन ने यह सब देखा और उसका मन गहरे आनंद से भर गया।', english: 'The journey was extremely arduous. They walked through forest paths filled with rocks and thorns. The sun blazed fiercely. Everyone suffered from thirst without water. A small frog grew weak and fell to the ground. Gopi immediately lifted the frog and carried it on his back. An old deer stumbled from pain in its legs. Two young monkeys stood on either side of the deer, supporting and walking with it. Kamban saw all this and felt deeply joyful in his heart.' },
      { native: 'शाम के समय वे एक बड़ी चट्टान के पास पहुँचे। चट्टान के किनारे एक विशाल साँप लेटा हुआ था। सारे जानवर काँपकर रुक गए। "साँप! साँप! हम मारे जाएँगे!" सब चिल्लाए। पर कम्बन शांति से आगे बढ़ा। उसने साँप से बात की। "मित्र, हम किसी को नुकसान पहुँचाने नहीं आए। हम पानी की तलाश में हैं। हमें रास्ता दे दो।" साँप उस विनम्र और निर्दोष आवाज़ को सुनकर चकित रह गया। वह धीरे से हटकर उन्हें रास्ता देने लगा।', english: 'At evening they reached a large rock. Near the edge of that rock lay a huge serpent. All the animals trembled and stopped in their tracks. "A snake! A snake! We are doomed!" they cried out. But Kamban walked forward calmly and peacefully. He spoke to the serpent. "Friend, we have not come to harm anyone. We are searching for water. Please give us way." The serpent was astonished to hear such a respectful and harmless voice. It slowly moved aside to let them pass.' },
      { native: 'रात में वे एक बड़े बरगद के पेड़ के नीचे रुके। कम्बन ने कहानी सुनाई। "पानी के अभाव के एक समय में एक चिड़िया ने अपने पंख इकट्ठे करके बारिश को बुलाया। उस चिड़िया का नाम कारिगई था। उसने अपने पंख फैलाकर आकाश की ओर देखते हुए नृत्य किया। आकाश ने उसका प्रेम और करुणा देखी और बारिश बरसा दी। ऐसे ही अगर हम शुद्ध मन से प्रयास करें, तो प्रकृति हमें रास्ता ज़रूर दिखाएगी," उसने कहा। जानवरों ने कम्बन की कहानी बड़े आनंद से सुनी। उनके भीतर फिर से आशा जाग उठी।', english: 'At night they rested under a great banyan tree. Kamban told a story. "In a time without water, a bird gathered all its feathers and called for rain. That bird\'s name was Karigai. She spread her feathers wide and danced looking up at the sky. The sky saw her love and compassion and poured down rain. Similarly, if we make efforts with a pure heart, nature will show us the way," he said. The animals listened to Kamban\'s story with great joy. Their hope was restored again.' },
      { native: 'अगले दिन सुबह उन्होंने फिर से अपनी यात्रा शुरू की। पहाड़ पर चढ़ते समय गोपी का पैर फिसला और वह नीचे गिर गया। वह डर से चिल्लाया। कम्बन तुरंत वहाँ पहुँचा। "डरो मत," कहते हुए उसने गोपी का हाथ मज़बूती से पकड़ लिया। बाकी जानवर भी मिलकर गोपी को ऊपर खींचने लगे। वह फिर उठा और चलने लगा। "जब तक हम साथ हैं, कोई भी बाधा हमें रोक नहीं सकती," कम्बन ने विश्वास से कहा।', english: 'The next morning they continued their journey again. While climbing up the mountain, Gopi slipped and fell down the slope. He cried out in fear. Kamban immediately rushed there. "Do not be afraid," he said, grasping Gopi\'s hand firmly. The other animals all joined together to pull Gopi back up safely. He stood up again and began to walk forward. "As long as we stay together, no obstacle can stop us," said Kamban with conviction.' },
      { native: 'दोपहर में जब सूरज सिर के ऊपर आया, वे एक हरी-भरी घाटी में पहुँचे। वहाँ एक निर्मल झरना खूबसूरती से बह रहा था। झरने का पानी धूप में चाँदी की तरह चमक रहा था। "पानी! पानी!" सारे जानवर एक साथ खुशी से चिल्लाए। वे दौड़कर झरने में कूद पड़े। पानी पिया। नहाए। खूब आनंद मनाया। गोपी खुशी से उछल-कूद करने लगा। मछलियाँ पानी में तैरने-कूदने लगीं। मेंढकों ने गीत गाए। उस दिन उस जंगल में एक बहुत बड़ा उत्सव हुआ।', english: 'At noon when the sun stood directly overhead, they arrived at a lush green valley. There, a crystal-clear waterfall was flowing beautifully. The water of the waterfall glistened like silver in the sunlight. "Water! Water!" all the animals cried out together in one joyful voice. They ran and jumped into the waterfall. They drank the water. They bathed. They celebrated with great happiness. Gopi danced and leaped with joy. Fish leaped and played in the water. Frogs sang their songs. That day in that forest, a tremendous celebration took place.' },
      { native: 'कम्बन झरने के किनारे बैठा सब कुछ देख रहा था। उसकी आँखों में संतोष और गहरी खुशी झलक रही थी। गोपी उसके पास आया। "कम्बन दादा, आपके बिना हम यह कभी नहीं कर पाते। धन्यवाद!" उसने कहा। कम्बन ने धीरे से सिर हिलाया। "मैंने कुछ नहीं किया बच्चे। हम सबने मिलकर यह किया है। आज तुमने सीखा कि अगर एकता और आशा हो, तो कोई भी संकट हमें हरा नहीं सकता। यही जीवन का सबसे बड़ा पाठ है। इसे हमेशा अपने दिल में रखना।"', english: 'Kamban sat on the bank of the waterfall and watched everything with peaceful joy. In his eyes there were satisfaction and deep happiness. Gopi came to him. "Kamban Anna, without you we could never have done this. Thank you!" he said. Kamban shook his head gently. "I did nothing, child. We all did it together. Today you have learned that if there is unity and hope, no crisis can defeat us. This is the greatest lesson of life. Keep it forever in your heart."' },
      { native: 'उस दिन से उसी झरने के किनारे सारे जानवरों ने अपना नया घर बना लिया। वह घाटी फिर से जीवन से भर उठी। पेड़ ऊँचे होते गए। फूल खूब खिले। बारिश फिर से धरती को आशीर्वाद देने लगी। कम्बन ने सौ सालों तक जो बुद्धि और प्रेम संजोया था, वह उस पूरे जंगल में फैल गया। आने वाली सारी पीढ़ियाँ बड़े गर्व से कम्बन की कहानी सुनाती रहीं। "एकता ही शक्ति है। प्रेम ही सबसे बड़ा हथियार है" — कम्बन के ये शब्द युगों-युगों तक गूँजते रहे।', english: 'From that day onward, all the animals built their new home on the banks of that waterfall. That valley was reborn with life. Trees grew tall. Flowers bloomed in abundance. Rain poured again blessing the land. The wisdom and love that Kamban had carried for one hundred years spread everywhere in that forest. All the generations to come told and retold Kamban\'s story with great pride. "Unity is strength. Love is the greatest weapon" — these words of Kamban echoed through the ages forever.' },
    ],
    moral: 'Unity, wisdom, and courage together can overcome any crisis in life.',
    moralNative: 'एकता, बुद्धि और साहस मिलकर जीवन के हर संकट को पार कर सकते हैं।',
  },

  // 2
  {
    title: 'Pongal Magic and the Sweet Rice',
    titleNative: 'पोंगल का जादू और मीठा चावल',
    category: 'Festivals & Traditions 🪔',
    emoji: '🌾',
    paragraphs: [
      { native: 'तमिलनाडु के एक छोटे से गाँव में — जिसका नाम वेप्पूर था — सब लोग बड़ी खुशी और संतोष से रहते थे। उस गाँव में ज़्यादातर लोग किसान थे। वे बारिश पर, धरती पर और सूरज पर भरोसा करके मेहनत करते थे। हर साल जब थाई महीना आता, तो उनका मन खुशी से भर उठता। क्योंकि थाई महीना पोंगल त्योहार का समय होता है। वह त्योहार उन्हें नई ज़िंदगी और नई उम्मीद देता था।', english: 'In a small village of Tamil Nadu — its name was Veppur — everyone lived with great happiness and contentment. Most of the people in that village were farmers. They worked depending on the rain, the earth, and the sun. Every year when the month of Thai arrived, their hearts would fill with great joy. Because Thai month is the time of the Pongal festival. That festival gave them renewed life and hope.' },
      { native: 'उस गाँव में एक छोटी लड़की रहती थी। उसका नाम कविता था। कविता को पोंगल त्योहार सबसे ज़्यादा पसंद था। पोंगल के दिन वह सुबह-सवेरे ही उठ जाती। माँ के साथ मिलकर घर की सफाई करती। आँगन में कोलम (रंगोली) बनाती। पुरानी मिट्टी की हांडी निकालकर बाहर रखती। उस दिन को वह दुनिया का सबसे सुंदर दिन मानती थी।', english: 'The Pongal festival was Kavitha\'s most beloved festival. On the day of Pongal she would wake up very early before dawn. She would clean the house together with her mother. She would draw kolam rangoli designs on the floor. She would bring out the old clay pot and place it outside. That day would be the most beautiful day in all the world for her.' },
      { native: 'इस साल पोंगल त्योहार से एक रात पहले, कविता अपने दादाजी के पास दौड़ी गई। "दादाजी, पोंगल की शुरुआत कैसे हुई? हम पोंगल क्यों बनाते हैं?" उसने उत्सुकता से पूछा। दादाजी मुस्कुराए। उन्होंने कविता को अपने पास बिठाया। "आओ बच्ची, मैं तुम्हें एक कहानी सुनाता हूँ," उन्होंने कहा। कविता बड़ी बेसब्री से इंतज़ार करने लगी।', english: 'The evening before this year\'s Pongal festival, Kavitha ran to her grandfather. "Grandpa, how did Pongal begin? Why do we make Pongal?" she asked eagerly. Grandpa smiled warmly. He made Kavitha sit beside him. "Come child, let me tell you a story," he said. Kavitha waited with great curiosity and anticipation.' },
      { native: '"कई सौ साल पहले, एक गाँव में भयंकर सूखा पड़ा था। बारिश नहीं हुई। ज़मीन पूरी तरह सूख गई। फसल नहीं हुई। लोग भूख से तड़पने लगे। उस गाँव के किसान इकट्ठा हुए। उन्होंने हाथ जोड़कर सूर्य भगवान से प्रार्थना की। उन्होंने अपना-अपना दुख उनसे कहा। दिल से आँसू बहाए। सूरज ने उनकी सच्ची और दिल से की गई प्रार्थना सुन ली," दादाजी ने कहा।', english: '"Many hundreds of years ago, a severe drought struck a village. There was no rain. The land dried up completely. There was no harvest. The people suffered greatly from hunger and hardship. The farmers of that village gathered together. They folded their hands and prayed to Lord Surya, the Sun God. They told him of each of their sorrows and hardships. They shed tears from their hearts. The Sun heard their honest and heartfelt prayer," said grandpa.' },
      { native: '"सूर्य भगवान ने बारिश भेजी। ज़मीन फिर से हरी-भरी हो गई। धान लहलहाने लगा। गन्ना बढ़ने लगा। किसान खुशी से झूम उठे। उन्होंने नया चावल लिया, उसमें गुड़ मिलाया, दूध डाला, और एक नई मिट्टी की हांडी सूरज की दिशा की ओर रखकर पोंगल बनाया। हांडी उफनकर बाहर बहने लगी। वे खुशी से चिल्लाए — \'पोंगलो पोंगल!\' उसी दिन से तमिल लोग हर साल यह त्योहार मनाते हैं," दादाजी ने कहानी पूरी की।', english: '"Lord Surya sent the rains. The land became green again. Paddy grew tall. Sugarcane flourished. The farmers leaped with great joy. They took new rice, added jaggery, poured fresh milk, placed a new clay pot facing the direction of the Sun, and cooked Pongal as an offering. The pot boiled over and overflowed. They shouted \'Pongalo Pongal!\' with jubilation. From that day forward, Tamil people celebrate this every year," grandpa concluded the story." ' },
      { native: 'कविता ने वह कहानी अपने दिल में बसा ली। अगली सुबह उसने अपनी माँ के साथ मिलकर आँगन में पोंगल बनाया। नई मिट्टी की हांडी को उसने गन्ने के पत्तों और हल्दी से सजाया। जब सूरज आकाश में उगा, कविता ने मन ही मन सूरज को धन्यवाद कहा। "हमारे किसानों को यह ज़िंदगी देने के लिए धन्यवाद!" उसने मन में कहा। उस पल उसके दिल में एक सुंदर, गर्मजोशी भरा एहसास भर उठा।', english: 'Kavitha stored that story deep in her heart. The next morning she joined her mother and cooked Pongal in the courtyard. She decorated the new clay pot with sugarcane leaves and turmeric. When the sun rose in the sky, Kavitha silently thanked the Sun from her heart. "Thank you for the life you gave to our farmers!" she said in her mind. In that moment, she felt a beautiful and warm experience fill her heart.' },
      { native: 'पोंगल की हांडी उफनकर मीठी भाप के साथ बाहर बहने लगी। "पोंगलो पोंगल!" कविता के पूरे परिवार ने मिलकर चिल्लाया। पड़ोसी भी आ गए। सब एक साथ जुट गए। सबने मिलकर पोंगल खाया। जब कविता ने मीठा पोंगल चखा, उसे मुँह में शहद जैसी मिठास महसूस हुई। "यह सिर्फ़ खाना नहीं है। यह हमारे लोगों की मेहनत का स्वाद है। यह हमारे आपसी रिश्ते का स्वाद है," दादाजी ने मुस्कुराते हुए कहा।', english: 'The Pongal pot boiled over and overflowed with sweet steam. "Pongalo Pongal!" shouted all of Kavitha\'s family members together. The neighbors came too. Everyone gathered as one. They ate Pongal together. When Kavitha tasted the sweet Pongal, she felt a sweetness like honey in her mouth. "This is not just ordinary food. This is the taste of our people\'s hard work. This is the taste of our connection," said grandpa with a smile.' },
      { native: 'मट्टु पोंगल के दिन गाँव की गायों को बाहर लाया गया। उन्हें प्यार से नहलाया गया। उन पर हल्दी लगाई गई। उनके सींगों पर फूलों की माला पहनाई गई। कविता ने एक गाय को गन्ना खिलाया। गाय ने धीरे से, प्यार भरी आँखों से कविता के हाथ से गन्ना खा लिया। "इन गायों ने हमारी खेती में मदद की है। आओ हम इनका आभार व्यक्त करें," पिताजी ने कहा। उस दिन कविता को जीवन की एक बिल्कुल नई समझ मिली।', english: 'On Mattu Pongal day, the village cattle were brought outside. They were bathed with care. Turmeric was applied on them. Garlands of flowers were placed on their horns. Kavitha gave a sugarcane to one of the cows. The cow slowly ate the sugarcane from Kavitha\'s hand with gentle eyes. "These cattle helped our farming. We express our gratitude to them," said her father. That day gave Kavitha a brand new understanding of life.' },
      { native: 'कानुम पोंगल के आखिरी दिन कविता के दादाजी ने सारे बच्चों को इकट्ठा किया। "पोंगल त्योहार हमें तीन बातें सिखाता है। पहली: हमेशा प्रकृति के प्रति कृतज्ञ रहो। दूसरी: मेहनत करने वालों का सम्मान करो। तीसरी: परिवार और समाज एक ही हैं," उन्होंने कहा। बच्चों ने खुशी से ताली बजाई। कविता ने उन शब्दों को हमेशा के लिए अपने दिल में सँजो लिया।', english: 'On the last day of the Kanum Pongal festival, Kavitha\'s grandfather gathered all the children together. "The Pongal festival teaches us three lessons. First: Be grateful to nature always. Second: Respect those who work hard. Third: Family and community are one," he said. The children clapped their hands in joy. Kavitha locked those words safely in her heart forever.' },
      { native: 'पोंगल त्योहार खत्म हो गया। पर उसकी मिठास कविता के दिल में पूरे साल बनी रही। उसने स्कूल में अपने दोस्तों को पोंगल की कहानी सुनाई। उन्होंने भी बड़ी दिलचस्पी से सुनी। "हमारी संस्कृति ही हमारा गौरव है," कविता ने सोचा। सूरज फिर उगेगा। बारिश फिर बरसेगी। धान फिर लहलहाएगा। पोंगल फिर आएगा। यह तमिल लोगों के जीवन का कभी न भूलने वाला, अनंत चक्र है।', english: 'The Pongal festival ended. But its sweet taste lingered in Kavitha\'s heart throughout the entire year. She told the story of Pongal to her friends at school. They listened with great interest and curiosity. "Our culture is our pride and glory," thought Kavitha. The sun will rise again. The rains will pour again. The paddy will grow again. Pongal will come again. This is the unforgettable, eternal cycle of Tamil people\'s lives.' },
    ],
    moral: 'Gratitude to nature, respect for labor, and unity in community are the true spirit of celebration.',
    moralNative: 'प्रकृति के प्रति कृतज्ञता, परिश्रम के प्रति सम्मान और समाज की एकता ही उत्सव की सच्ची भावना है।',
  },

  // 3
  {
    title: 'King Chola and the Bell of Justice',
    titleNative: 'चोल राजा और न्याय की घंटी',
    category: 'Kings & Scholars 🏰',
    emoji: '🏰',
    paragraphs: [
      { native: 'प्राचीन चोल राज्य में एक राजा राज करता था। उसका नाम मणिवर्मन था। वह न्याय और करुणा के लिए प्रसिद्ध राजा था। उसके शासन में लोग खुशी-खुशी रहते थे। खेत हरे-भरे और समृद्ध थे। व्यापार शानदार ढंग से फलता-फूलता था। हर कोई कहता — "मणिवर्मन राजा की जय हो!" पर राजा को इस बात की कोई परवाह नहीं थी कि लोग उसके बारे में क्या कहते हैं। वह हमेशा अपनी प्रजा और उनकी भलाई के बारे में ही सोचता रहता था।', english: 'In the ancient Chola kingdom there lived a king. His name was Manivarman. He was a king renowned for his justice and compassion. Under his rule, people lived happily. Fields were green and prosperous. Trade flourished magnificently. Everyone would say "Long live King Manivarman!" But the king did not care about what was said about him. He always thought only about his people and their welfare.' },
      { native: 'मणिवर्मन ने अपने महल के सामने एक बड़ी घंटी टँगवाई। उस घंटी की रस्सी किसी भी दिन, किसी भी समय खींची जा सकती थी। जब घंटी बजती, राजा खुद वहाँ आता। उसने घोषणा की थी कि कोई भी, कभी भी न्याय माँग सकता है। पाँच साल बीत गए। वह घंटी कई बार बजी। हर बार राजा आया और निष्पक्षता से न्याय दिया। उसकी कीर्ति पूरे राज्य में फैल गई।', english: 'Manivarman hung a great bell in front of his palace. Anyone at all could pull the rope of that bell. When the bell rang, the king himself would come in person. He announced that anyone could seek justice at any time of day or night. Five years passed. That bell was rung many times. Each and every time, the king came and delivered justice with fairness. His fame spread throughout the entire kingdom.' },
      { native: 'एक दिन आधी रात को घंटी बजी। पहरेदार चौंक गए। आधी रात को घंटी कौन बजाएगा? वे बाहर आए। घंटी की रस्सी में एक सफेद गधा उलझा हुआ था। वह बार-बार रस्सी को काट रहा था, जिससे घंटी ज़ोर से बज रही थी। पहरेदार हँस पड़े। "यह तो बस एक गधा है! भगाओ इसे!" उन्होंने कहा। पर राजा वह आवाज़ सुनकर खुद बाहर आ गया।', english: 'One night at midnight, the bell was struck. The guards were astonished. Who would ring the bell at midnight? They came outside. On the rope of the bell was a white donkey. It bit the rope again and again making the bell ring loudly. The guards laughed. "This is just a donkey! Get away!" they said dismissively. But the king heard the sound and came outside himself.' },
      { native: '"एक गधा भी न्याय माँग सकता है। जाओ पता लगाओ कि क्या हुआ है," राजा ने दृढ़ता से कहा। पहरेदार गधे के पीछे-पीछे गए। वह शहर के एक किनारे बनी कार्यशाला में जाकर रुका। वहाँ उस गधे का बच्चा एक पत्थर पीसने वाली मशीन में फँस गया था और साँस लेने के लिए तड़प रहा था। वह छोटा बच्चा भयंकर पीड़ा में छटपटा रहा था। राजा ने तुरंत आदेश दिया। मज़दूरों ने बच्चे को मशीन से बाहर निकाला।', english: 'Even a donkey can seek justice. Go and find out what happened," said the king firmly. The guards followed the donkey. It stopped at a workshop on the edge of the city. There, the donkey\'s young foal had got trapped in a stone-grinding machine and was struggling to breathe. The young foal was writhing in terrible pain. The king gave an immediate order. The workers rescued the foal from the machine.' },
      { native: 'राजा ने कार्यशाला के मालिक को बुलाया। "तुम्हारी मशीन ने एक जीव की जान लेने की कोशिश की। यह तुम्हारी लापरवाही है। अब से रात में यह मशीन नहीं चलेगी। साथ ही उस गधी और उसके बच्चे के लिए एक अच्छा आश्रय दो," उसने आदेश दिया। मालिक काँपते हुए माफ़ी माँगने लगा। "राजा एक गधे को भी न्याय देते हैं!" — यह बात पूरे शहर में फैल गई।', english: 'The king summoned the factory owner. "Your machine attempted to kill a living creature. This is your negligence. Henceforth, you shall not operate this machine at night. Furthermore, provide a good shelter and living space for the donkey and its young foal," he commanded firmly. The owner trembled and begged forgiveness. "The king delivers justice even to a donkey!" the entire city spoke of this with wonder and admiration.' },
      { native: 'वह गधा हर रोज़ महल के सामने आकर खड़ा होने लगा। राजा को देखते ही उसकी आँखों में कृतज्ञता की चमक दिखती। लोगों ने यह देखा। "राजा का न्याय सिर्फ़ इंसानों के लिए नहीं है। यह हर जीव के लिए है," लोग बड़े आदर से कहने लगे। बच्चे आकर गधे को खाना खिलाते। वह गधा चोल राज्य का एक प्रसिद्ध और प्रिय नागरिक बन गया।', english: 'That donkey came and stood in front of the palace every day. When it saw the king, there was a light of gratitude visible in its eyes. The people witnessed this. "The king\'s justice is not only for humans. It is for all living beings," the people said with great reverence. Children came and gave food to the donkey. That donkey became a famous and beloved citizen of the Chola kingdom.' },
      { native: 'साल बीतते गए। राजा मणिवर्मन बूढ़ा हो गया। उसने अपने बेटे को बुलाया। "बेटा, एक राजा को सिर्फ़ ताकत के बल पर राज नहीं करना चाहिए। उसे न्याय और करुणा के साथ जीना चाहिए। जब भी कोई न्याय माँगने आए — इंसान हो या जानवर — उसे कभी नज़रअंदाज़ मत करना। हर जीव में ईश्वर का अंश होता है," उसने कहा। ये शब्द चोल वंश में पीढ़ी-दर-पीढ़ी श्रद्धा से माने गए।', english: 'Years passed. King Manivarman grew old. He called his son to him. "My son, a king must not live only by strength and power. He must live by justice and compassion. Whenever anyone comes seeking justice — be it a human or an animal — never ignore them. In every living being there is a reflection of God," he said. Those words were followed faithfully through generations in the Chola dynasty.' },
      { native: 'आज भी वह कहानी सुनाई जाती है। इतिहास में इसे "राजा मणिवर्मन की न्याय घंटी" के नाम से जाना जाता है। बच्चे स्कूल में यह कहानी पढ़ते हैं। "न्याय सिर्फ़ शक्तिशाली लोगों के लिए नहीं होता। सच्चा न्याय वही है जो शक्तिहीनों तक भी पहुँचे," वे यह सीखते हैं। उस न्याय घंटी की ध्वनि आज भी हमारे दिलों में गूँजती है।', english: 'Even today that story is told. It found its place in history under the name "King Manivarman\'s Bell of Justice." Children study this story in schools. "Justice is not only for the powerful. True justice is that which reaches those without power," they learn. The sound of that bell of justice still rings in our hearts even today.' },
    ],
    moral: 'True justice protects every living being, regardless of status or species.',
    moralNative: 'सच्चा न्याय हर जीव की रक्षा करता है — चाहे उसकी हैसियत या प्रजाति कुछ भी हो।',
  },

  // 4
  {
    title: 'The Brave Girl of the Kaveri River',
    titleNative: 'कावेरी नदी की साहसी बेटी',
    category: 'Village Fables 🌾',
    emoji: '🌊',
    paragraphs: [
      { native: 'तंजावुर ज़िले में कावेरी नदी के किनारे एक छोटा सा गाँव था। उसका नाम नीलावेली था। उस गाँव में सब लोग किसान थे। कावेरी का पानी ही उनकी ज़िंदगी था। उस नदी के बिना उस गाँव का कोई अस्तित्व नहीं था। गाँव का हर बच्चा कावेरी को माँ मानकर उसकी पूजा करता था। उस गाँव में एक छोटी लड़की रहती थी। उसका नाम नल्ली था। नल्ली बारह साल की थी। वह बेहद साहसी थी। उसे किसी भी खतरे से डर नहीं लगता था।', english: 'On the banks of the Kaveri River in Thanjavur district there was a small village. Its name was Neelaveeli. Everyone in that village were farmers. The water of the Kaveri was their very life. Without that river, that village would not exist. Every child in the village worshipped the Kaveri as their mother. In that village there was a little girl named Nalli. Nalli was twelve years old. She was extremely courageous. She feared no danger whatsoever.' },
      { native: 'एक बरसात के मौसम में कावेरी में बाढ़ आ गई। सिर्फ़ एक रात में पानी कई फीट ऊपर चढ़ आया। गाँव वाले सुरक्षित जगहों की तरफ़ भागे। बच्चे रोने लगे। बुज़ुर्ग घबरा गए। वह रात बहुत काली थी। बिजली आकाश को चीर रही थी। बादल गरज रहे थे। नल्ली अपने परिवार के साथ एक ऊँची जगह पर खड़ी थी। अचानक उसे कहीं से किसी छोटे बच्चे के रोने की आवाज़ सुनाई दी।', english: 'One monsoon season the Kaveri flooded. In just one night the water rose many feet high. The villagers ran to safer places. Children wept. The elderly panicked. That night was extremely dark. Lightning split the sky. Thunder roared loudly. Nalli stood on a mound with her family members. Suddenly she heard the crying sound of a small child from somewhere.' },
      { native: '"वहाँ एक बच्चा है!" नल्ली ज़ोर से चिल्लाई। सबने सुना। "किसी का बच्चा बाढ़ में फँस गया है!" किसी ने कहा। बड़े-बुज़ुर्ग हिचकिचाने लगे। बाढ़ का पानी बहुत तेज़ी से बह रहा था। अँधेरे में कुछ भी दिखाई नहीं दे रहा था। किसी में भी आगे आने का साहस नहीं था। उस पल नल्ली ने एक पल भी नहीं सोचा। उसने हाथ में एक रस्सी पकड़ी और तेज़ पानी में कूद पड़ी।', english: '"There is a child over there!" cried Nalli loudly. Everyone heard her. "Someone\'s child is trapped in the flood!" someone said. The elders hesitated nervously. The flood water was flowing extremely fast. Nothing was visible in the darkness. No one stepped forward with courage. At that moment Nalli did not think even for a second. She grabbed a rope in her hand. She jumped into the rushing water.' },
      { native: 'बाढ़ की धारा बेहद ज़ोरदार थी। नल्ली तैरते हुए उस रोने की आवाज़ की तरफ़ बढ़ी। अँधेरे में उसे एक पेड़ की डाल दिखाई दी। उस डाल को एक दो साल का बच्चा पकड़े हुए ठंड और डर से काँप रहा था। नल्ली ने उस बच्चे को कसकर गले लगाया। रस्सी बाँधी। किनारे पर खड़े लोगों ने रस्सी खींची। बच्चा और नल्ली दोनों सुरक्षित किनारे पर पहुँच गए।', english: 'The current of the flood was extremely powerful and fierce. Nalli swam toward the crying voice in the darkness. In the darkness she spotted a tree branch. Clinging to that branch was a two-year-old child, trembling with cold and fear. Nalli embraced the child tightly. She tied the rope around them. The people on the shore pulled the rope. Both the child and Nalli reached the bank safely.' },
      { native: 'गाँव वाले नल्ली को घेरकर खड़े हो गए। "तुम सचमुच बहुत साहसी हो!" सबने उसकी तारीफ़ की। नल्ली अभी भी ठंड से काँप रही थी। पर उसकी आँखों में गहरा संतोष था। बच्चे की माँ ने नल्ली को कसकर गले लगाया। "मेरे बच्चे को बचाने के लिए धन्यवाद! तुम न होतीं तो यह चला जाता," उसने रोते हुए कहा। नल्ली मुस्कुराई। "जब कोई मुसीबत में हो, तो उसकी मदद करना हमारा फ़र्ज़ है," उसने सीधे शब्दों में कहा।', english: 'The villagers surrounded Nalli with great warmth. "You are so very brave!" everyone praised her. Nalli was still trembling from the cold. But in her eyes there was deep satisfaction. The child\'s mother embraced Nalli tightly. "Thank you for saving my child! Without you it would have been gone," she said with tears streaming down her face. Nalli smiled gently. "When anyone is in difficulty, it is our duty to help them," she said simply.' },
      { native: 'बाढ़ उतर गई। गाँव फिर से अपनी सामान्य ज़िंदगी में लौट आया। पर नल्ली का नाम पूरे गाँव में फैल गया। गाँव की एक बुज़ुर्ग महिला नल्ली के पास आई। "बेटी, तुमने माँ कावेरी का साहस पाया है। कावेरी कभी पीछे नहीं हटती। वह हर बाधा को पार करते हुए आगे बहती रहती है। तुम भी बिल्कुल वैसी ही हो," उसने कहा। नल्ली ने ये शब्द सुने और उसका दिल गर्मजोशी से भर उठा।', english: 'The flood receded. The village returned to its normal state. But Nalli\'s name spread throughout the entire village. An elderly woman of the village came to Nalli. "Child, you have received the courage of Mother Kaveri. Kaveri never retreats. She flows forward through every obstacle and difficulty. You are exactly the same," she said. Nalli heard those words and felt her heart fill with warmth.' },
      { native: 'उस साल के आखिरी उत्सव में गाँव के बुज़ुर्गों ने नल्ली को एक तोहफ़ा दिया। वह एक चाँदी की कंगन थी, जिस पर कावेरी नदी का चिह्न उकेरा हुआ था। "माँ कावेरी से तुमने साहस सीखा है। आने वाली पीढ़ियाँ तुम्हें हमेशा याद रखें," बुज़ुर्ग ने गर्व से कहा। नल्ली ने वह कंगन पहन लिया। कृतज्ञता के आँसू उसकी आँखों से बह निकले।', english: 'In the celebrations at the end of that year, the village elders gave Nalli a gift. It was a silver bangle. On it was engraved the symbol of the Kaveri River. "From Mother Kaveri you have learned courage. May future generations remember you," said the elder with great pride. Nalli wore that bangle. Tears flowed from her eyes with gratitude.' },
      { native: 'नल्ली बड़ी हुई। वह एक तैराकी प्रशिक्षक बनी। उसने गाँव के सारे बच्चों को तैरना सिखाया। "हमारी कावेरी हमारी रक्षा करती है। पर हमें भी खुद की रक्षा करना आना चाहिए। तैरना हर बच्चे को सीखना चाहिए," उसने दृढ़ता से कहा। उस गाँव में आज भी हर बच्चा तैरना सीखता है। नल्ली का साहस एक प्रिय परंपरा बन गया।', english: 'Nalli grew up. She became a swimming trainer and instructor. She taught all the children of the village to swim. "Our Kaveri protects us. But we must also know how to protect ourselves. Swimming is something every child must learn," she said firmly. In that village even today every child learns to swim. Nalli\'s courage has become a cherished tradition.' },
    ],
    moral: 'Courage and quick action in the face of danger can save lives and inspire generations.',
    moralNative: 'खतरे के सामने साहस और तुरंत लिया गया फैसला जानें बचा सकता है और पीढ़ियों को प्रेरित कर सकता है।',
  },

  // 5
  {
    title: 'Tenali Raman and the Golden Mangoes',
    titleNative: 'तेनाली रामन और सोने के आम',
    category: 'Kings & Scholars 🏰',
    emoji: '👑',
    paragraphs: [
      { native: 'विजयनगर साम्राज्य में महान राजा कृष्णदेवराय बड़ी शान से राज करते थे। उस दौर में तेनाली रामन नाम का एक हाज़िरजवाब और बुद्धिमान कवि राजा की सभा में रहता था। तेनाली रामन बेहद चतुर था। उसकी हर मज़ाकिया बात के पीछे एक गहरा दर्शन छिपा होता था। जो वह कहता, उसे पहली बार में कोई नहीं समझ पाता। पर बाद में जब लोग उस बारे में सोचते, तो उसमें छिपा गहरा सच उजागर हो जाता।', english: 'In the Vijayanagar Empire, the great king Krishnadevaraya ruled with glory. In those times, a witty and brilliant poet named Tenali Raman served in the king\'s court. Tenali Raman was extremely intelligent. Hidden in his jokes and humor there was always a profound philosophy. No one would initially understand what he said. But when they thought about it later, the deep truth within it would become clear.' },
      { native: 'एक दिन राजा की सभा में एक धनी व्यापारी आया। वह एक बड़ा लकड़ी का संदूक लेकर आया था। "महाराज! इस संदूक में सोने के आम हैं। पर ये साधारण आम नहीं हैं। अगर किसी को ये खिलाए जाएँ, तो उसे संपूर्ण ज्ञान मिल जाएगा। पर एक शर्त है — हर आम की कीमत एक लाख वराहन है," उसने कहा। यह सुनकर राजा को बड़ी दिलचस्पी हुई।', english: 'One day a wealthy merchant came to the king\'s court. He carried a large wooden chest with him. "Your Majesty! Inside this chest are golden mangoes. But these are not ordinary mangoes. If you make anyone eat one, they will attain all wisdom and knowledge. But there is one condition — each mango costs one lakh varaham," he said. Hearing this, the king became very interested and curious.' },
      { native: 'राजा ने एक आम खरीदकर खाया। "बहुत मीठा है। पर मुझे नहीं पता कि ज्ञान आया या नहीं," उन्होंने कहा। व्यापारी हँस पड़ा। "महाराज! ज्ञान तुरंत प्रकट नहीं होता। कुछ दिनों में दिखेगा," उसने कहा। तेनाली रामन यह सब सुन रहा था। उसने कुछ नहीं कहा। पर उसकी आँखों में एक तीखी, समझदार चमक दिखाई दे रही थी।', english: 'The king bought one mango and ate it. "It is very sweet. But I cannot tell if wisdom has arrived," he said. The merchant laughed. "Your Majesty! Wisdom does not become apparent immediately. It will show itself in a few days," he said. Tenali Raman was listening to all this. He said nothing at all. But in his eyes there was a keen and sharp light of understanding.' },
      { native: 'अगले दिन तेनाली रामन राजा के पास आया। "महाराज, मैंने एक अद्भुत पेड़ खोजा है। उस पेड़ पर चाँदी के फल लगते हैं। हर फल खाने से लंबी उम्र मिलती है। पर एक शर्त है — उस पेड़ तक जाने के लिए एक मार्गदर्शक चाहिए। वह मार्गदर्शक मैं ही हूँ। फीस है दो लाख," उसने कहा। राजा को यह सुनकर बड़ा गुस्सा आया।', english: 'The next day Tenali Raman came to the king. "Your Majesty, I have discovered a wonderful tree. On that tree grow silver fruits. If anyone eats one of those fruits they will receive a long life. But there is one condition — to go to that tree a guide is needed. I am that guide. The fee is two lakhs," he said. The king became very angry at this.' },
      { native: '"तेनाली! तुम यह क्या कह रहे हो? यह तो मूर्खता है!" राजा चिल्लाए। तेनाली रामन शांति से मुस्कुराया। "महाराज, कल उस व्यापारी ने क्या कहा था? उसने कहा था कि सोने का आम खाने से ज्ञान मिलेगा। उसके लिए आपने एक लाख दिए। मेरा चाँदी का फल भी बिल्कुल वैसा ही है। जब बात विश्वास की हो, तो कीमत उसी हिसाब से तय हो जाती है," उसने कहा।', english: '"Tenali! What are you saying? This is nonsense!" shouted the king. Tenali Raman smiled calmly. "Your Majesty, what did that merchant say yesterday? He said if you eat a golden mango, wisdom will come. For that you paid one lakh. My silver fruit is the same kind of thing. When it comes to belief and trust, price is determined accordingly," he said.' },
      { native: 'राजा एक पल के लिए सोच में पड़ गए। उन्हें सच्चाई समझ में आ गई। उस व्यापारी ने जिसे सोने का आम कहा था, वह असल में बस एक साधारण आम था। पर "ज्ञान देगा" कहने से उसकी कीमत बिल्कुल अलग हो गई। "तेनाली! तुमने सही कहा। मुझे धोखा दिया गया। उस व्यापारी को बुलाओ। मेरा पैसा वापस लो," उन्होंने आदेश दिया।', english: 'The king thought for a moment. The truth became clear to him. What that merchant called a golden mango was merely an ordinary mango. But because he said it would "give wisdom," the price became different entirely. "Tenali! You have spoken correctly. I was deceived. Call that merchant. Get my money back," he commanded firmly.' },
      { native: 'तेनाली रामन ने सभा में मौजूद सबको संबोधित किया। "हम में से हर कोई अंधे विश्वास की वजह से धोखा खा सकता है। किसी भी चीज़ की कीमत उसकी असली प्रकृति से आँकनी चाहिए, सिर्फ़ खोखले शब्दों से नहीं। बुद्धिमत्ता सिर्फ़ किताबी ज्ञान में नहीं होती। सच को पहचानने की क्षमता ही असली बुद्धिमत्ता है," उसने कहा। सभा में मौजूद सबने सहमति में सिर हिलाया।', english: 'Tenali Raman addressed everyone in the court. "Each and every one of us can be deceived through misplaced trust and belief. The value of any thing must be measured by its true and genuine nature. Not by mere words and claims. Intelligence is not only in bookish learning. The ability to recognize truth is the real wisdom," he said. Everyone assembled in the court nodded in agreement.' },
      { native: 'उस दिन राजा कृष्णदेवराय ने तेनाली रामन को एक सुनहरा वस्त्र भेंट किया। "तुम्हारी बुद्धि हमेशा मेरी रक्षा करे," उन्होंने कहा। तेनाली रामन ने आदरपूर्वक झुककर प्रणाम किया। उस दिन से तेनाली रामन की चतुराई भरी कहानियाँ पूरे राज्य में फैल गईं। वे आज भी बच्चों को सुनाई जाती हैं। "हँसते हुए भी सोचना चाहिए" — यही तेनाली का जीवन-दर्शन है।', english: 'That day King Krishnadevaraya gave Tenali Raman a golden shawl as a gift. "May your intelligence always protect and guide me," he said. Tenali Raman bowed with respect. From that day forward, the stories of Tenali Raman\'s brilliant wit spread throughout the entire kingdom. They are still told to children even today. "Even while laughing, one must think" — this is the philosophy of Tenali Raman.' },
    ],
    moral: 'True wisdom lies in recognizing truth, not in being dazzled by false promises.',
    moralNative: 'सच्ची बुद्धिमत्ता सत्य को पहचानने में है, न कि झूठे वादों की चमक-दमक में खो जाने में।',
  },

  // 6
  {
    title: 'Ganesha and the Mango of Wisdom',
    titleNative: 'गणेश जी और ज्ञान का आम',
    category: 'Mythology & Legends 🔱',
    emoji: '🔱',
    paragraphs: [
      { native: 'कैलाश पर एक दिन भगवान शिव ने अपने दोनों पुत्रों — गणेश और मुरुगन — को बुलाया। "तुम्हारे लिए एक प्रतियोगिता है। यहाँ सिर्फ़ एक ही आम है। जो भी सबसे पहले तीनों लोकों की परिक्रमा करके लौटेगा, उसे यह आम मिलेगा। यह ज्ञान का आम है। इसे खाने से संपूर्ण ज्ञान प्राप्त होता है," उन्होंने कहा। मुरुगन तुरंत अपने मोर वाहन पर सवार होकर उड़ गए। गणेश जी बैठकर सोचने लगे।', english: 'One day in Kailasa, Lord Shiva called his sons Ganesha and Murugan. "There is a competition for you. There is only one mango here. Whoever first circumambulates all three worlds and returns will receive this mango. This is a mango of wisdom. If eaten it grants complete knowledge and enlightenment," he said. Murugan immediately mounted his peacock vehicle and flew away. Ganesha sat and thought carefully.' },
      { native: 'गणेश जी धीरे से उठे। उन्होंने अपने छोटे से चूहे वाहन की ओर देखा। "इस वाहन पर तीनों लोकों की परिक्रमा करने में बहुत लंबा समय लगेगा। पर ज्ञान बाहर खोजने की चीज़ नहीं है। वह तो यहीं है," उन्होंने सोचा। गणेश जी ने अपने माता-पिता, शिव और पार्वती के चारों ओर तीन बार परिक्रमा की और उन्हें प्रणाम किया। "पिता माता सर्वम् — माता-पिता ही सब कुछ हैं," उन्होंने कहा।', english: 'Ganesha slowly arose. He looked at his small mouse vehicle. "It will take a very long time to circumambulate all three worlds in this vehicle. But wisdom is not something to be sought outside. It is right here," he thought. Ganesha walked around his father Shiva and mother Parvati three times and bowed to them. "Pitha Matha Sarvam — Parents are everything," he said.' },
      { native: 'भगवान शिव यह देखकर चकित रह गए। "पुत्र, मुझे समझाओ," उन्होंने कहा। गणेश जी मुस्कुराए। "पिताजी, तीनों लोक आप ही में समाए हुए हैं। मेरी माँ और पिता ही मेरा संसार हैं। अगर मैं उनकी परिक्रमा करूँ, तो यह तीनों लोकों की परिक्रमा करने के बराबर है," उन्होंने कहा। भगवान शिव खुलकर मुस्कुराए। "तुम विजयी हुए। यह आम तुम्हारा है," उन्होंने कहा।', english: 'Lord Shiva was astonished at this. "Son, explain yourself," he said. Ganesha smiled. "Father, all three worlds exist within you. My mother and father are my world. If I circumambulate them, it is equal to circumambulating all three worlds," he said. Lord Shiva smiled broadly. "You have won. This mango belongs to you," he said.' },
      { native: 'मुरुगन ने तीनों लोकों की परिक्रमा पूरी की। वे हाँफते हुए वापस लौटे। पर जब तक वे लौटे, गणेश जी को वह आम पहले ही मिल चुका था। मुरुगन चकित रह गए। "यह कैसे संभव है?" उन्होंने पूछा। भगवान शिव ने समझाया। मुरुगन समझ गए। "सिर्फ़ मेरे बड़े भाई ही ऐसा सोच सकते हैं। यह सिर्फ़ चतुराई नहीं है — यह सच्चा ज्ञान है," उन्होंने आदरपूर्वक कहा।', english: 'Murugan circumambulated all three worlds. He returned panting and breathless. But when he arrived, Ganesha had already received the mango. Murugan was astonished. "How is this possible?" he asked. Lord Shiva explained. Murugan understood. "Only my elder brother can think like this. This is not mere cleverness — this is true wisdom," he said with admiration.' },
      { native: 'उस दिन से गणेश जी को "अग्रणिम" — यानी सबसे पहले पूजे जाने वाले — के रूप में पूजा जाने लगा। किसी भी काम की शुरुआत में सबसे पहले गणेश जी की पूजा करने की परंपरा शुरू हुई। "माता-पिता का सम्मान करना तीनों लोकों की पूजा करने के बराबर है" — यह विचार पूरे भारत में फैल गया। आज भी विनायक चतुर्थी के दिन यह कहानी बड़ी श्रद्धा से सुनाई जाती है।', english: 'From that day Ganesha was worshipped as "Agranima" — the one who comes before everything. The custom of worshipping Ganesha first before beginning any task or venture started. The philosophy that "Respecting one\'s parents is equal to worshipping all three worlds" spread throughout all of India. Even today on Vinayaka Chaturthi this story is told with great devotion.' },
      { native: '"माँ, हम गणेश जी की पूजा सबसे पहले क्यों करते हैं?" एक बच्चे ने पूछा। माँ ने उसे यह कहानी सुनाई। बच्चे की आँखें आश्चर्य से बड़ी हो गईं। "तो फिर मैं, आप, दादाजी और दादी — क्या आप सब मेरे तीनों लोक हैं?" उसने पूछा। माँ ने आँखों में आँसू भरकर बच्चे को गले लगा लिया। "हाँ बेटा। हम ही तुम्हारा संसार हैं। और तुम ही हमारा संसार हो," उसने पूरे प्रेम से कहा।', english: '"Mother, why do we worship Ganesha first?" a child asked. The mother told this story. The child\'s eyes widened with wonder. "Then you, father, grandfather, and grandmother — are all of you my three worlds?" it asked. The mother embraced the child with tears in her eyes. "Yes child. We are your world. And you are our world," she said with all the love in her heart.' },
    ],
    moral: 'True wisdom is recognizing that our parents are our greatest universe.',
    moralNative: 'यह पहचानना कि हमारे माता-पिता ही हमारा सबसे बड़ा संसार हैं, यही सच्ची बुद्धिमत्ता है।',
  },

  // 7
  {
    title: 'The Singing Banyan Tree',
    titleNative: 'गाता हुआ बरगद का पेड़',
    category: 'Morals & Wisdom 🌟',
    emoji: '🌳',
    paragraphs: [
      { native: 'एक गाँव के बीचोबीच एक विशाल बरगद का पेड़ खड़ा था। वह पेड़ शायद हज़ार साल से भी ज़्यादा पुराना रहा होगा। उसकी जड़ें ज़मीन में गहराई तक धँसी हुई थीं। उसकी शाखाएँ आकाश की ओर फैली हुई थीं। उस पेड़ की छाया में गाँव के लोग इकट्ठा होते थे। झगड़े सुलझाते थे। कहानियाँ सुनाते थे। बच्चे खेलते थे। वह पेड़ गाँव के दिल जैसा था।', english: 'In the middle of a village stood a great banyan tree. That tree must have been more than a thousand years old. Its roots were buried deep in the earth. Its branches stretched up toward the sky. In the shade of that tree, the village people would gather together. They would settle disputes. They would tell stories. Children would play. That tree was like the heart of the village.' },
      { native: 'गाँव वाले कहा करते थे — "यह पेड़ गाता है। रात में जब हवा चलती है, तो पेड़ के पत्ते एक तरह का संगीत बजाते हैं। वह संगीत सुनने से मन शांत हो जाता है। सारी चिंताएँ दूर हो जाती हैं।" बच्चे इस बात को सच मानते थे। वे रात में पेड़ के नीचे आकर बैठते और हवा की आवाज़ सुनते। एक हल्की सी ध्वनि आती। उन्हें आराम से नींद आ जाती।', english: 'The villagers would say: "This tree sings. When the wind comes at night, the leaves of the tree produce a kind of music. If you hear that music, the mind becomes calm and peaceful. Worries disappear." The children believed this. They would come and sit under the tree at night and listen to the wind. A soft sound would come. They would fall peacefully asleep.' },
      { native: 'एक बार दूसरे शहर से एक व्यापारी आया। उसने पेड़ को देखा। "यह पेड़ बहुत कीमती है। अगर इसे काटकर बेच दूँ, तो बहुत पैसा मिलेगा," उसने सोचा। वह गाँव के बुज़ुर्ग के पास गया। "मैं यह पेड़ खरीदना चाहता हूँ। मैं अच्छी कीमत दूँगा," उसने कहा। गाँव के बुज़ुर्ग ने साफ़ मना कर दिया। "यह पेड़ बिकाऊ नहीं है। यह पूरे गाँव की संपत्ति है," उन्होंने कहा।', english: 'Once a merchant came from another town. He looked at the tree. "This tree is extremely valuable. If I cut and sell it, I can get a lot of money," he thought. He went to the village elder. "I will buy this tree. I will give a good price for it," he said. The village elder refused firmly. "This tree is not for sale. It is the property of the entire village," he said.' },
      { native: 'व्यापारी ने हार नहीं मानी। वह रात में अकेले आया। पेड़ काटने के लिए कुल्हाड़ी लेकर आया। पर जैसे ही वह पेड़ के पास पहुँचा, उसे एक अजीब सी आवाज़ सुनाई दी। एक गहरी, मधुर, पर साथ ही चेतावनी देती हुई आवाज़ कहीं से आ रही थी। व्यापारी डर से काँप उठा। उसने मुड़कर देखा। वहाँ कोई नहीं था। पर आवाज़ रुकी नहीं। वह डरकर वहाँ से भाग गया।', english: 'The merchant did not give up. He came alone at night. He took an axe to cut the tree. But when he approached the tree, a strange sound was heard. A deep, melodious, yet warning voice came from somewhere. The merchant trembled with fear. He turned to look around. There was no one. But the voice did not stop. He ran away from there in great fear.' },
      { native: 'अगले दिन उसने गाँव वालों को बताया। "वह पेड़ बोला! मुझे आवाज़ सुनाई दी!" गाँव वाले हँस पड़े। "पेड़ नहीं बोला। हवा और पत्तों ने मिलकर आवाज़ बनाई। पर तुम्हारे मन की आवाज़ ने उसे एक चेतावनी की तरह सुना। क्योंकि तुम कुछ गलत करने आए थे," गाँव के बुज़ुर्ग ने कहा। व्यापारी ने सिर झुका लिया। उसे अपने आप पर शर्म महसूस हुई।', english: 'The next day he told the village people. "That tree spoke! A voice was heard!" he said. The village people laughed kindly. "The tree did not speak. The wind and the leaves together produced a sound. But your own conscience heard that sound as a warning. Because you came to do something wrong," said the village elder. The merchant bowed his head. He felt ashamed of himself.' },
      { native: '"पेड़ हमें ऑक्सीजन देते हैं। छाया देते हैं। बारिश को बुलाते हैं। हमें इनकी रक्षा करनी चाहिए। ये हमारे अतीत की बचत हैं। ये आने वाली पीढ़ी के प्रति हमारा कर्तव्य हैं," गाँव के बुज़ुर्ग ने बड़ी बुद्धिमानी से कहा। व्यापारी ने सच्चे मन से माफ़ी माँगी। उस दिन से उसने गाँव में लगन से पेड़ लगाने शुरू कर दिए। उसका मन उस काम को करके पूरी तरह संतुष्ट हो गया।', english: 'Trees give us oxygen. They give shade. They call the rains. We must protect them. They are the savings of our past. They are our duty to future generations," said the village elder with great wisdom. The merchant honestly sought forgiveness. From that day he planted trees in the village with dedicated effort. His mind accepted that work with complete satisfaction.' },
      { native: 'साल बीत गए। वह बरगद का पेड़ आज भी खड़ा है। व्यापारी द्वारा लगाए गए पेड़ बड़े हो गए। गाँव हरा-भरा हो गया। "जो पेड़ काटने आया था, उसने हज़ार पेड़ लगाए," गाँव वाले कहते हैं। वह बरगद का पेड़ आज भी गाता है। जब हवा चलती है, उसके पत्ते एक लय में झूमते हैं। वह आवाज़ सबके लिए एक याद दिलाती है: "प्रकृति से प्रेम करो। वह तुम्हारी सुरक्षा करेगी।"', english: 'Years passed. That banyan tree still stood tall. The trees planted by the merchant grew tall and strong. The village became lush and green. "The one who came to cut one tree planted a thousand trees," the villagers would say. That banyan tree still sings today. When the wind comes, its leaves beat like a rhythm. That sound is a reminder to everyone: "Treat nature with love. It will protect you safely."' },
    ],
    moral: 'Nature is our guardian. Protecting trees is protecting ourselves and future generations.',
    moralNative: 'प्रकृति हमारी रक्षक है। पेड़ों की रक्षा करना खुद हमारी और आने वाली पीढ़ियों की रक्षा करना है।',
  },

  // 8
  {
    title: 'The Honest Shepherd Boy',
    titleNative: 'ईमानदार चरवाहा लड़का',
    category: 'Morals & Wisdom 🌟',
    emoji: '🐑',
    paragraphs: [
      { native: 'एक गाँव में एक गरीब परिवार रहता था। उस परिवार में एक छोटा लड़का था। उसका नाम शेखर था। वह हर रोज़ गाँव की भेड़ें चराने ले जाता था। पहाड़ की ढलानों पर भेड़ें चराता था। गर्मी हो या बरसात, उसने कभी अपना काम नहीं छोड़ा। उसकी माँ हमेशा कहती थी: "शेखर, ईमानदारी ही हमारी असली दौलत है। कभी सच का साथ मत छोड़ना।"', english: 'In a village there lived a poor family. In that family there was a young boy. His name was Sekar. Every day he would take the village sheep out to graze. He herded the sheep on the mountain slopes. In summer and in rainy season alike, he never shirked his duty. His mother would say: "Sekar, honesty alone is our wealth. Never abandon truth."' },
      { native: 'एक दिन शेखर पहाड़ी रास्ते पर चल रहा था। उसे एक सोने का सिक्का मिला। वह मिट्टी में दबा हुआ था। बारिश के पानी ने मिट्टी को हटा दिया था, जिससे वह बाहर दिख गया। शेखर ने वह सिक्का उठाया। वह बहुत पुराना और कीमती लग रहा था। उसने सोचा: "यह किसी का खोया हुआ है। मुझे इसे लौटाना चाहिए।"', english: 'One day Sekar was walking along a mountain path. He found a gold coin. It had been buried in the mud. Rain water had shifted the mud and it appeared. Sekar picked up the coin. It appeared to be very old and valuable. He thought to himself: "Someone lost this. I must return it."' },
      { native: 'शेखर गाँव वापस लौटा। वह गाँव के मुखिया के पास गया। "यह सोने का सिक्का पहाड़ पर मिला है। यह किसी का खोया हुआ है। गाँव के सब लोगों से पूछिए। यह ज़रूर किसी न किसी का होगा," उसने कहा। गाँव का मुखिया चकित रह गया। "बच्चे, तुम इस सिक्के को अपने पास रख सकते हो। किसी को पता नहीं चलेगा," उसने कहा। शेखर ने मना कर दिया। "नहीं। यह मेरा नहीं है।"', english: 'Sekar returned to the village. He went to the village head. "This gold coin was found on the mountain. Someone lost it. Ask all the villagers. It belongs to someone," he said. The village head was astonished. "Child, you can keep this coin. No one will know," he said. Sekar refused firmly. "No. This is not mine."' },
      { native: 'गाँव में सबसे पूछा गया। एक बूढ़ा व्यापारी आगे आया। "मेरा सोने का सिक्का! मैंने इसे खो दिया था! यह मेरे पिता की याद में मिला उपहार है। मैं पाँच सालों से इसे ढूँढ़ रहा हूँ," उसने कहा। उसकी आँखों से आँसू बह निकले। शेखर ने वह सिक्का उसे लौटा दिया। व्यापारी ने शेखर को कसकर गले लगाया। "बच्चे, तुमने मुझे सिर्फ़ सिक्का नहीं लौटाया। तुमने मुझे मेरे पिता की याद वापस दी है," उसने कहा।', english: 'They asked throughout the village. An old merchant came forward. "My gold coin! I lost it! This is a memorial gift from my father. I have been searching for five years," he said. Tears flowed from his eyes. Sekar gave the coin back to him. The merchant embraced Sekar tightly. "Child, you have returned to me not just the coin. You have returned the memory of my father," he said.' },
      { native: 'व्यापारी शेखर को कोई इनाम देना चाहता था। "मैं तुम्हें जो चाहो वह दूँगा। पैसा चाहिए? गहने चाहिए?" उसने पूछा। शेखर ने सिर हिलाया। "मेरी माँ कहती हैं: सच ही असली दौलत है। मैंने सच लौटाया है। यही मेरा इनाम है," उसने सीधे शब्दों में कहा। गाँव के सारे लोगों ने शेखर की तारीफ़ की।', english: 'The merchant wanted to give Sekar a reward. "I will give you whatever you want. Do you want money? Do you want jewels?" he asked. Sekar shook his head. "My mother says: Truth alone is wealth. I returned truth. That itself is my reward," he said simply. All the villagers praised and honored Sekar.' },
      { native: 'वह व्यापारी शेखर की माँ के पास गया। "आपका बेटा बहुत ईमानदार है। मैं उसकी पढ़ाई में मदद करूँगा," उसने कहा। शेखर स्कूल में भर्ती हुआ। उसने बड़ी लगन से पढ़ाई की। साल बीत गए। शेखर एक न्यायाधीश बना। उस गाँव में उसने जो न्याय के काम किए, वे आज भी याद किए जाते हैं।', english: 'That merchant came to Sekar\'s mother. "Your son is extremely honest. I will help him study and get education," he said. Sekar enrolled in school. He studied with great dedication. Years passed. Sekar became a judge. The acts of justice he performed in that village are still talked about to this day.' },
      { native: '"सच्चाई की हमेशा जीत होती है" — यह सिर्फ़ एक कहावत नहीं है। शेखर का जीवन इसका जीता-जागता सबूत है। जिस छोटे लड़के ने एक छोटा सा सोने का सिक्का ईमानदारी से लौटाया था, उसने अपनी पूरी ज़िंदगी ईमानदारी को अपना मार्गदर्शक बनाकर जी। "बच्चों, सच बोलने से मत डरो। एक दिन वही सच तुम्हारी रक्षा करेगा," वह अपनी अदालत में हमेशा कहता था।', english: '"Truth always wins" is not just a proverb. Sekar\'s life is a testimony to it. That little boy who honestly returned a small gold coin lived his entire life with honesty as his guiding light. "Children, do not be afraid to speak the truth. One day that very truth will protect you," he would always say in his court.' },
    ],
    moral: 'Honesty is the greatest wealth. What we give honestly will return to us multiplied.',
    moralNative: 'ईमानदारी ही सबसे बड़ी दौलत है। जो हम ईमानदारी से देते हैं, वह कई गुना होकर हमारे पास लौटता है।',
  },

  // 9
  {
    title: 'The Dancing Peacock of Andhra',
    titleNative: 'आंध्र का नाचता मोर',
    category: 'Panchatantra & Animals 🦊',
    emoji: '🦚',
    paragraphs: [
      { native: 'आंध्र प्रदेश की हरी-भरी पहाड़ियों में एक घना जंगल था। उस जंगल में सैकड़ों पक्षी रहते थे। पर उन सबमें सबसे सुंदर पक्षी था एक मोर। उसका नाम श्रीकांत था। श्रीकांत के पंख नीले और हरे रंग के अद्भुत मेल में चमकते थे। जब वह नाचता, तो उसके पंख धूप में हीरों की तरह चमक उठते थे।', english: 'In the green mountains of Andhra Pradesh there was a dense forest. In that forest hundreds of birds lived. But the most beautiful bird of all was a peacock. Its name was Srikant. Srikant\'s plumage was in a wonderful combination of blue and green colours. When it danced, the plumage shimmered like diamonds in the sunlight.' },
      { native: 'बारिश आने पर श्रीकांत नाचने लगता। जब आकाश में बादल घिरते, वह अपने पंख फैला देता। उसके पैर एक लय में थिरकते। सिर झूमता। यह नृत्य देखने के लिए जंगल के सारे जानवर आते थे। हिरण बैठकर देखते। बंदर पेड़ की डालों से लटककर देखते। कछुए धीरे-धीरे आकर एक पत्थर पर चढ़कर खड़े होकर देखते। सबको श्रीकांत का नृत्य बहुत पसंद था।', english: 'Srikant would dance when the rains came. When clouds darkened the sky, it would spread its plumage wide. Its feet would beat a rhythm. Its head would sway gracefully. To watch this dance, all the animals of the forest would come. Deer would sit and watch. Monkeys would hang from tree branches and watch. Tortoises would slowly come and climb on a rock to watch. Everyone loved Srikant\'s dance very much.' },
      { native: 'पर एक दिन एक बाज़ आया। उसने श्रीकांत को तिरस्कार भरी नज़रों से देखा। "यह मोर सिर्फ़ नाचना ही जानता है। इसे तो उड़ना भी नहीं आता। इसमें ऐसी क्या बड़ी बात है?" उसने मज़ाक उड़ाया। श्रीकांत ने सिर झुका लिया। "यह सच है। मैं ठीक से उड़ नहीं पाता," उसने कहा। बाज़ ज़ोर से हँसा। "तुम एक शर्मनाक प्राणी हो!" उसने ताना मारा।', english: 'But one day an eagle came. It looked at Srikant with contempt. "This peacock only knows how to dance. It doesn\'t even know how to fly properly. What is so great about that?" it said mockingly. Srikant bowed its head. "That is true. I cannot fly well," it said. The eagle laughed loudly. "You are a shameful creature!" it mocked.' },
      { native: 'श्रीकांत का मन दुखी हो गया। वह नाचना ही भूल गया। बारिश आने पर भी उसने अपने पंख नहीं फैलाए। जंगल के जानवर आकर देखते। "श्रीकांत, तुम नाच क्यों नहीं रहे?" वे पूछते। वह चुप रहता। पूरा जंगल शांत हो गया। बारिश गिरती रही। पर मोर के नृत्य के बिना जंगल अधूरा-सा महसूस होने लगा।', english: 'Srikant\'s heart was troubled. It forgot to dance altogether. Even when rain came, it did not spread its plumage. The animals of the forest came and looked. "Srikant, why are you not dancing?" they asked. It remained silent. The entire forest became silent. Rain fell. But without the peacock\'s dance, the forest felt incomplete.' },
      { native: 'एक बूढ़ा कछुआ श्रीकांत के पास आया। "बेटे, बाज़ ने तुम्हारा मज़ाक उड़ाया कि तुम्हें उड़ना नहीं आता। पर क्या बाज़ तुम्हारी तरह नाच सकता है? हर किसी के पास कोई न कोई अनोखा हुनर होता है। वही हुनर हमारी पहचान है। बाज़ आकाश में उड़ता है। तुम धरती पर नाचते हो। दोनों ही अद्भुत हैं," उसने कहा।', english: 'An old tortoise came to Srikant. "My son, the eagle mocked you saying you cannot fly. But can the eagle dance like you? Each one of us has a unique talent. That talent is our identity. The eagle soars in the sky. You dance on the earth. Both are wonderful and beautiful," it said.' },
      { native: 'श्रीकांत ने सिर उठाया। आकाश में काले बादल घिर रहे थे। उसने धीरे-धीरे अपने पंख फैलाए। हवा चलने लगी। उसने नाचना शुरू किया। हर कदम में एक लय। हर मोड़ में एक नया रंग। जंगल के सारे जानवर देखने के लिए इकट्ठा हो गए। बाज़ भी आया। उसने श्रीकांत का नृत्य देखा। उसकी आँखों में आश्चर्य और गहरा सम्मान दिखाई दिया।', english: 'Srikant stood tall and proud. Dark clouds were gathering in the sky. It slowly spread its plumage wide. The wind began to blow. It started to dance. In every step a rhythm. In every turn a new colour. All the animals of the forest gathered to watch. The eagle came too. It watched Srikant\'s dance. In its eyes there were both amazement and deep respect.' },
      { native: '"मुझे माफ़ कर दो," बाज़ ने कहा। "तुम्हारा नृत्य अद्भुत है। मैं यह नहीं कर सकता। मैंने गलत कहा था।" श्रीकांत मुस्कुराया। "तुम भी बहुत खूबसूरती से उड़ते हो। आकाश की ऊँचाई से तुम जो नज़ारा देखते हो, वह मैं नहीं देख सकता। हम सब अपने-अपने तरीके से अनोखे हैं।" उस दिन से बाज़ और मोर दोस्त बन गए।', english: '"I ask for forgiveness," said the eagle. "Your dance is extraordinary. I cannot do this. I spoke wrongly." Srikant smiled. "You too fly beautifully. The view you see from the height of the sky is something I cannot see. We are each unique and special in our own way." From that day the eagle and the peacock became friends.' },
      { native: 'जब बारिश गिरती, श्रीकांत नाचता। बाज़ आकाश में चक्कर लगाता। बाकी जानवर उनकी दोस्ती देखकर चकित रह जाते। "हर हुनर का सम्मान हो। हर जीव अनोखा है" — यह सीख उस जंगल में हमेशा के लिए बस गई।', english: 'When the rain fell, Srikant would dance. The eagle would circle in the sky above. The other animals were amazed to see their friendship. "May every talent be respected. Every living being is unique" — this lesson remained forever in that forest as an enduring truth.' },
    ],
    moral: 'Every being has a unique gift. Never mock what you cannot do yourself.',
    moralNative: 'हर जीव में एक विशेष हुनर होता है। जो तुम खुद नहीं कर सकते, उसका मज़ाक कभी मत उड़ाओ।',
  },

  // 10
  {
    title: 'The Loyal Elephant of Tanjore',
    titleNative: 'तंजावुर का वफ़ादार हाथी',
    category: 'Panchatantra & Animals 🦊',
    emoji: '🐘',
    paragraphs: [
      { native: 'तंजावुर के बड़े मंदिर में एक प्रसिद्ध हाथी रहता था। उसका नाम कुम्की था। कुम्की चालीस सालों से उस मंदिर में था। मंदिर के उत्सवों में कुम्की सबसे आगे चलता था। उसके माथे पर कुमकुम लगाया जाता था। उसे सोने के आभूषण पहनाए जाते थे। लोग कुम्की को देखकर बड़े प्रेम से प्रणाम करते थे। "कुम्की भगवान का वाहन है," वे कहते थे।', english: 'In the great Tanjore temple there was a famous elephant. Its name was Kumki. Kumki had been in the temple for forty years. In the temple festivals, Kumki walked at the front of the procession. Kumkum was applied on its forehead. Golden ornaments were adorned on it. People saw Kumki and bowed to it with great love. "Kumki is the vehicle of the divine," they would say.' },
      { native: 'कुम्की की देखभाल एक महावत करता था। उसका नाम रामासामी था। रामासामी बचपन से ही कुम्की के साथ रहता आया था। वह हर रोज़ कुम्की को नहलाता, खाना खिलाता और उससे बातें करता। कुम्की भी सिर्फ़ रामासामी पर ही भरोसा करता था। "ये दोनों जान एक ही हैं," मंदिर के पंडित कहा करते थे।', english: 'The one who looked after Kumki was a mahout worker. His name was Ramasamy. Ramasamy had lived with Kumki since childhood. Every day he would bathe Kumki, give it food, and talk to it. Kumki too trusted only Ramasamy. "These two lives are as one," the temple priests would say.' },
      { native: 'एक साल के उत्सव में बहुत बड़ी भीड़ जमा हुई। रात का उत्सव बड़ी धूमधाम से चल रहा था। कुम्की जुलूस में चल रहा था। अचानक एक बड़ा पटाखा फट गया। उस भयंकर आवाज़ से कुम्की घबरा गया। वह घबराकर भागने लगा। लोग चीखने लगे। बच्चे काँपने लगे। किसी में कुम्की के पास जाने की हिम्मत नहीं थी।', english: 'One year at the festival a very large crowd had gathered. The night festival was taking place with great grandeur. Kumki walked in the procession. Suddenly a large firecracker burst with a tremendous noise. Kumki was startled by the sound. It began to run in panic. People screamed. Children trembled. No one had the courage to approach Kumki.' },
      { native: 'रामासामी दौड़कर आया। उसने कुम्की का नाम पुकारा। "कुम्की! कुम्की! मैं रामासामी हूँ! मैं तुम्हारे साथ हूँ। डरो मत!" वह चिल्लाया। कुम्की ने वह आवाज़ सुनी। वह मुड़ा। उसने रामासामी को देखा। उसकी आँखों में अभी भी डर था। पर रामासामी को देखते ही वह धीरे-धीरे शांत होने लगा।', english: 'Ramasamy ran forward. He called Kumki\'s name. "Kumki! Kumki! I am Ramasamy! I am here with you. Don\'t be afraid!" he shouted. Kumki heard that voice. It turned around. It looked at Ramasamy. Fear was still visible in its eyes. But when it saw Ramasamy, it slowly began to calm down.' },
      { native: 'रामासामी ने कुम्की के माथे पर हाथ रखा। "मैं यहाँ हूँ। मैं तुम्हें नहीं छोड़ूँगा," उसने कहा। कुम्की ने अपनी सूँड़ रामासामी के कंधे पर रख दी। वह धीरे-धीरे पूरी तरह शांत हो गया। लोगों ने यह देखा। "देखो! विश्वास हर डर और हथियार को हरा देता है!" उन्होंने कहा।', english: 'Ramasamy placed his hand on Kumki\'s forehead. "I am here. I will not leave you," he said. Kumki placed its trunk on Ramasamy\'s shoulder. It calmed down slowly, slowly. The people saw this. "Look! Loyalty and trust conquers all weapons and fears!" they said.' },
      { native: 'कुम्की कई सालों तक जीवित रहा। एक दिन वह बहुत बीमार पड़ गया। वैद्य आए। पर उसने रामासामी के अलावा किसी को भी अपने पास नहीं आने दिया। रामासामी अकेला ही उसके पास बैठा रहा। कुम्की ने अपनी सूँड़ से उसका हाथ पकड़ लिया। बहुत देर तक ऐसे ही रहा। फिर धीरे-धीरे उसने अपनी आँखें मूँद लीं। रामासामी रो पड़ा। मंदिर में घंटी बजी। लोगों ने आँसुओं के साथ कुम्की को श्रद्धांजलि दी।', english: 'Kumki lived for many years. One day it fell very ill. Doctors came. But it would not let anyone near except Ramasamy. Ramasamy alone stayed by its side. Kumki held his hand with its trunk. It stayed like that for a long time. Then slowly it closed its eyes. Ramasamy wept. A bell rang in the temple. People paid their tearful respects to Kumki.' },
      { native: '"कुम्की सिर्फ़ एक हाथी नहीं था। वह एक सच्चा दोस्त था" — तंजावुर के लोग आज भी यह कहते हैं। उस मंदिर में कुम्की की एक मूर्ति स्थापित की गई। उत्सवों में लोग आकर उस मूर्ति को प्रणाम करते हैं। "विश्वास ही दोस्ती की नींव है। दोस्ती ही जीवन का अर्थ है" — कुम्की के जीवन का यह पाठ आज भी याद किया जाता है।', english: '"Kumki was not just an elephant. It was a faithful friend" — the people of Tanjore say this even today. A statue of Kumki was placed in that temple. During festivals people come and bow to that statue. "Trust is the foundation of friendship. Friendship is the meaning of life" — the life lesson of Kumki is remembered and honored even today.' },
    ],
    moral: 'Loyalty and unconditional trust between two souls transcends all barriers.',
    moralNative: 'दो आत्माओं के बीच वफ़ादारी और निःस्वार्थ विश्वास हर बाधा को पार कर जाता है।',
  },

  // 11
  {
    title: 'Diwali Lights in the Dark Forest',
    titleNative: 'घने जंगल में दीये की रोशनी',
    category: 'Festivals & Traditions 🪔',
    emoji: '🪔',
    paragraphs: [
      { native: 'एक घने जंगल के बीचोबीच एक अकेला संकरा रास्ता था। उस रास्ते पर रात में कोई नहीं जाता था। कारण यह था कि उस रास्ते पर एक पुराना मंडप था। वह कई सालों से इस्तेमाल में नहीं था। लोग उसे डर की नज़र से देखते थे। "उस मंडप में बुरी शक्तियाँ रहती हैं," वे कहते थे। बच्चे वहाँ जाने से डरते थे।', english: 'In the middle of a dense forest there was a single narrow path. At night, no one would travel along that path. The reason was that along that way there was an old mandapam. It had been unused for many years. People looked at it with great fear. "Evil forces dwell in that mandapam," they would say. Children were afraid to go anywhere near it.' },
      { native: 'एक दिवाली के दिन, एक छोटा लड़का रास्ता भटककर उस जंगल में आ गया। उसका नाम अर्जुन था। रात हो चुकी थी। उसे घर वापस जाने का रास्ता नहीं मिल रहा था। वह डर से काँपने लगा। उसने वह पुराना मंडप देखा। "अगर मैं यहाँ रुक जाऊँ, तो आज रात सुरक्षित रहूँगा," उसने सोचा। पर उसे लोगों की कही बातें याद आ गईं। वह हिचकिचाया।', english: 'One Diwali day, a young boy wandered off and came into the forest. His name was Arjun. Night fell. He did not know the way back home. He trembled with fear. He saw the old mandapam. "If I stay here, I will be safe for this night," he thought. But what the people said came back to his mind. He hesitated.' },
      { native: 'अर्जुन ने अपने थैले से एक दिवाली का दीया निकाला। उसकी माँ हमेशा दिवाली के दिन उसे एक छोटा मिट्टी का दीया देती थी। "यह दीया तुम्हारी रक्षा करेगा," वह कहती थी। अर्जुन ने वह दीया जला लिया। एक छोटी सी लौ जगमगा उठी। अँधेरा कुछ कम हो गया। वह मंडप के भीतर चला गया।', english: 'Arjun took out a Diwali lamp from his bag. His mother usually gave him a small clay lamp on Diwali day. "This lamp will protect you," she would say. Arjun lit that lamp. A small flame of light came. The darkness receded somewhat. He entered inside the mandapam.' },
      { native: 'मंडप के अंदर अर्जुन चकित रह गया। वहाँ एक बूढ़ी दादी बैठी थीं। वे ठंड और डर से काँप रही थीं। "बच्चे! तुम कौन हो? इस रात में यहाँ कैसे आ गए?" उन्होंने पूछा। अर्जुन ने सब समझाया। दादी भी रास्ता भटककर वहाँ आ गई थीं। उनके पैर में दर्द था और वे चल नहीं पा रही थीं। "मैं आपकी मदद करूँगा," अर्जुन ने कहा।', english: 'Inside the mandapam, Arjun was astonished. There was an old grandmother sitting there. She was trembling with cold and fear. "Child! Who are you? How did you come here on this night?" she asked. Arjun explained. The grandmother had also wandered and got lost. She could not walk due to pain in her legs. "I will help you," said Arjun.' },
      { native: 'अर्जुन ने मंडप के भीतर का रास्ता साफ़ किया। दादी को खाना खिलाया। पूरी रात वह दीया जलता रहा। बाहर उत्सव की आवाज़ें सुनाई दे रही थीं। दिवाली के पटाखे आकाश को रंग-बिरंगा कर रहे थे। पर उस मंडप में एक बहुत ही शांत, अनोखी दिवाली मनाई जा रही थी।', english: 'Arjun cleaned the path inside the mandapam. He gave food to the grandmother. He kept that lamp burning throughout the entire night. Outside, festival sounds were heard. Diwali fireworks split the sky with colour. But inside that mandapam, a very peaceful and quiet Diwali celebration took place.' },
      { native: 'सुबह-सवेरे गाँव वाले अर्जुन को खोजते हुए वहाँ आए। उन्होंने मंडप देखा। बाहर से एक बहुत छोटी सी रोशनी दिख रही थी। वे अंदर आए। अर्जुन और दादी दोनों वहाँ मौजूद थे। "यहाँ कोई बुरी शक्ति नहीं है! एक दीये ने अँधेरे को भगा दिया। एक बच्चे के प्रेम ने एक बुज़ुर्ग की जान बचा ली," लोगों ने आश्चर्य से कहा।', english: 'At dawn the village people came searching for Arjun. They looked at the mandapam. A small faint light was visible from outside. They came inside. Arjun and the grandmother were both there. "There are no evil forces here! One lamp drove away the darkness. A child\'s love saved an elderly person," the people said with wonder.' },
      { native: 'उस दिन से वह मंडप गाँव वालों के मिलने की जगह बन गया। हर दिवाली के दिन गाँव के सब लोग वहाँ आकर दीये जलाते हैं। उस मंडप का नाम "अर्जुन का दीया" रख दिया गया। "दीया सिर्फ़ रोशनी नहीं है। यह एक उम्मीद है। यह प्रेम का प्रतीक है," गाँव के बुज़ुर्ग ने कहा।', english: 'From that day the mandapam became a gathering place for the people. On Diwali day all the villagers would come there and light lamps. They named the mandapam "Arjun\'s Lamp." "A lamp is not merely light. It is a hope. It is a symbol of love," said the village elder.' },
    ],
    moral: 'A single lamp of courage and love can illuminate even the darkest of places.',
    moralNative: 'साहस और प्रेम से जला एक छोटा सा दीया सबसे अँधेरी जगह को भी रोशन कर सकता है।',
  },

  // 12
  {
    title: 'The Potter and the Secret Conch',
    titleNative: 'कुम्हार और रहस्यमयी शंख',
    category: 'Arts & Music 🎶',
    emoji: '🏺',
    paragraphs: [
      { native: 'एक गाँव में एक कुम्हार रहता था। उसका नाम मारीमुत्थु था। वह मिट्टी से सुंदर चीज़ें बनाने में बड़ा माहिर था। उसके बनाए मिट्टी के बर्तन पूरे गाँव में मशहूर थे। उसके बनाए हर बर्तन में एक कलात्मक सुंदरता झलकती थी। पर मारीमुत्थु का एक बड़ा सपना था। वह एक शंख बनाना चाहता था। एक बहुत ही खास शंख।', english: 'In a village there lived a potter. His name was Marimuthu. He was an expert in making beautiful objects from clay. The clay pots he made were famous throughout the village. In every pot he made there was an artistic beauty. But Marimuthu had one great dream. He wanted to make a conch shell. A very special conch.' },
      { native: 'बचपन में उसने मंदिर में शंख बजने की आवाज़ सुनी थी। वह आवाज़ उसे बेहद मोहित कर गई। "क्या यह आवाज़ मिट्टी में बनाई जा सकती है? अगर मैं मिट्टी का शंख बनाऊँ, तो क्या उसे बजाने पर वही आवाज़ आएगी?" उसने सोचा। सालों तक उसने यह सपना अपने दिल में संजोए रखा।', english: 'As a child he heard the sound of a conch being blown in the temple. That sound captivated him deeply. "Can this sound be made in clay? If I make a clay conch, when it is blown will the same sound come?" he wondered. For years he had kept this dream in his heart.' },
      { native: 'मारीमुत्थु ने मिट्टी का शंख बनाना शुरू किया। पहली कोशिश नाकाम रही। दूसरी कोशिश भी नाकाम रही। दसवीं कोशिश भी नाकाम रही। गाँव वाले हँसने लगे। "कुम्हार शंख बनाने की कोशिश कर रहा है! यह असंभव है!" वे कहते। मारीमुत्थु यह सब सुनता। पर उसने हार नहीं मानी।', english: 'Marimuthu began making a clay conch. The first attempt failed. The second attempt failed. The tenth attempt also failed. The villagers laughed. "The potter is trying to make a conch! This is impossible!" they said. Marimuthu heard them. But he did not give up.' },
      { native: 'एक दिन एक बूढ़ा शिल्पकार वहाँ आया। उसने मारीमुत्थु के मिट्टी के शंख देखे। "तुम सही आकार में, सही मौसम में, सही कोण पर काम नहीं कर रहे। शंख के भीतर एक घुमाव होता है। वही घुमाव ध्वनि पैदा करता है। इसे मिट्टी में भी बनाया जा सकता है," उसने कहा। मारीमुत्थु ने बड़ी उत्सुकता से यह सुना।', english: 'One day an old sculptor came. He looked at Marimuthu\'s clay conches. "You are not working with the right shape, at the right season, at the right angle. Inside a conch there is a spiral. It is that spiral which produces the sound. It can be made in clay," he said. Marimuthu listened with great eagerness and interest.' },
      { native: 'मारीमुत्थु ने फिर से शुरुआत की। इस बार उसने शिल्पकार के मार्गदर्शन के अनुसार काम किया। उसने मिट्टी को सही दबाव से गूँधा। घुमाव को सही कोण पर आकार दिया। उसे भट्टी में पकाया। ठंडा होने दिया। मारीमुत्थु ने उसे उठाया। उसका दिल तेज़ी से धड़क रहा था। उसने फूँक मारी।', english: 'Marimuthu started again. This time he worked according to the sculptor\'s guidance. He kneaded the clay with the right pressure. He shaped the spiral at the right angle. It was fired in the kiln. It cooled. Marimuthu picked it up. His heart was beating rapidly. He blew into it.' },
      { native: 'एक सुंदर, गहरी ध्वनि निकली। वह ध्वनि बिल्कुल मंदिर के शंख जैसी थी। मारीमुत्थु खुशी से रो पड़ा। "उन्होंने कहा था यह असंभव है। पर अगर विश्वास और मेहनत हो, तो सब कुछ संभव है," उसने सोचा। गाँव वालों ने वह आवाज़ सुनी। वे चकित रह गए। उन्होंने मारीमुत्थु की खूब तारीफ़ की।', english: 'A beautiful, deep sound came from it. That sound was like the sound of a conch from a temple. Marimuthu wept with joy. "They said it was impossible. But if there is belief and effort, everything is possible," he thought. The village people heard the sound. They were astonished. They praised Marimuthu.' },
      { native: 'वह मिट्टी का शंख मंदिर में रखा गया। दिवाली के उत्सव में उसे बड़ी शान से बजाया गया। वह "मिट्टी के बेटे द्वारा बनाया गया शंख" के नाम से मशहूर हो गया। मारीमुत्थु ने यह कला गाँव के युवाओं को सिखाई। "कला सिर्फ़ हाथ का हुनर नहीं है। यह आत्मा की अभिव्यक्ति है। कला पर विश्वास रखो। कला तुम्हारी रक्षा करेगी," उसने कहा।', english: 'That clay conch was placed in the temple. During the Diwali festival it was blown with great ceremony. It became famous as "The conch made by the son of the earth." Marimuthu taught this art to the young people of the village. "Art is not just handwork. It is the expression of the soul. Have faith in art. Art will protect you," he said.' },
    ],
    moral: 'Persistence and passion can turn an impossible dream into beautiful reality.',
    moralNative: 'लगन और जुनून एक असंभव सपने को भी सुंदर हकीकत में बदल सकते हैं।',
  },

  // 13
  {
    title: 'Onam Boat Race in Kerala',
    titleNative: 'केरल की ओणम नाव दौड़',
    category: 'Festivals & Traditions 🪔',
    emoji: '🚣',
    paragraphs: [
      { native: 'जब केरल के अल्लापुझा के बैकवाटर में ओणम का त्योहार आता है, तो एक भव्य उत्सव मनाया जाता है। उस उत्सव का मुख्य आकर्षण होता है वल्लम काली — साँप नाव दौड़। जब सौ नाविक एक ही नाव में मिलकर पतवार चलाते हैं, तो पानी उफनने और झाग बनने लगता है। वह दृश्य आँखों के लिए किसी उत्सव से कम नहीं होता। इस दौड़ को देखने के लिए पूरे केरल से लोग उमड़ पड़ते हैं।', english: 'When the Onam festival comes to the Alappuzha backwaters of Kerala, a grand celebration takes place. The crown of that celebration is Vallam Kali — the snake boat race. When a hundred oarsmen row together in one boat, the water churns and froths magnificently. That sight itself is a festival for the eyes. People from all over Kerala gather to watch this competition.' },
      { native: 'एक गाँव में एक जवान, मज़बूत लड़का रहता था। उसका नाम आदित्यन था। उसका सपना था वल्लम काली में हिस्सा लेना। पर वह बहुत छोटा था। "तुम्हें और बड़ा होना होगा। वल्लम काली सिर्फ़ बड़ों के लिए है," गाँव वाले कहते थे। आदित्यन निराश हो जाता। पर उसने हार नहीं मानी। हर रोज़ सुबह वह समुद्र में तैरता। पतवार चलाना सीखता रहा।', english: 'In a village there lived a strong young boy. His name was Adithyan. His dream was to participate in Vallam Kali. But he was very young and small. "You must become bigger. Vallam Kali is only for adults," the villagers said. Adithyan was disappointed. But he did not give up. Every morning he swam in the sea. He learned the skill of rowing.' },
      { native: 'एक साल की प्रतियोगिता में अचानक एक संकट आ गया। आदित्यन के गाँव की साँप नाव टीम का एक सदस्य आखिरी पल में बीमार पड़ गया। एक जगह खाली थी। टीम के मुखिया किसी को ढूँढ़ने लगे। "आदित्यन को जाने दो," किसी ने कहा। "वह तो लड़का है!" दूसरे ने कहा। "पर वह बहुत अच्छा पतवार चलाता है। हर रोज़ अभ्यास करता है," मुखिया ने कहा।', english: 'One year a sudden crisis arose at the competition. One member of Adithyan\'s village snake boat team fell ill at the last minute. One place was empty. The team leader searched for someone to fill it. "Let Adithyan go," said someone. "He is a young boy!" said another. "But he rows very well. He practices every day," said the team leader.' },
      { native: 'आदित्यन नाव में चढ़ गया। वह घबराहट से काँप रहा था। उसके बगल में बैठे बुज़ुर्ग ने कहा: "डरो मत। हम सब मिलकर पतवार चलाएँगे। एक ही लय। एक ही मन। एक ही लक्ष्य।" आदित्यन ने आँखें बंद कर लीं। एक गहरी साँस ली। दौड़ शुरू हुई। "ऐ ऐ ऐ ऐ!" लयबद्ध पुकार गूँज उठी। नाव पानी को चीरते हुए आगे बढ़ने लगी।', english: 'Adithyan got into the boat. He trembled with nervousness. The elder beside him said: "Do not be afraid. We will row together. One rhythm. One mind. One goal." Adithyan closed his eyes. He took a deep breath. The competition began. "Ai ai ai ai!" the rhythmic call rose up. The boat cut through the water and surged forward.' },
      { native: 'आदित्यन खुद को भूल गया। वह अब सिर्फ़ एक पतवार नहीं था। वह एक बड़ी टीम का हिस्सा था। हर एक चाल में उसने इसे महसूस किया। हर एक खिंचाव में वह और मज़बूत होता गया। नाव बहुत तेज़ी से आगे बढ़ी। किनारे से भीड़ चिल्लाई — "आदित्यन! आदित्यन!" उसका परिवार खुशी से रो पड़ा।', english: 'Adithyan forgot himself completely. He was not just a single oar. He was part of a great team. In every stroke he felt it. In every pull he grew. The boat went very fast. The crowd on the shore shouted. "Adithyan! Adithyan!" His family wept with joy.' },
      { native: 'उनकी नाव ने पहला स्थान जीता। आदित्यन घुटनों के बल बैठ गया और आँखें बंद कर लीं। "एकता जीत लाती है। जब लक्ष्य एक हो, तो उम्र और कद कोई बाधा नहीं," उसने सोचा। टीम के सदस्यों ने उसे उठाकर जश्न मनाया। "तुम्हारे बिना यह जीत संभव नहीं थी," उन्होंने कहा।', english: 'Their boat won first place. Adithyan knelt down and closed his eyes. "Unity brings victory. When there is one goal, age and size are no barrier," he thought. The team members lifted him up and celebrated. "Without you this victory would not have been possible," they said.' },
      { native: 'वह वल्लम काली की जीत पूरे केरल में चर्चा का विषय बन गई। खबर फैली — "एक छोटे लड़के ने एक बड़ी जीत में हिस्सा लिया।" आदित्यन बड़ा हुआ। वह एक मशहूर वल्लम काली खिलाड़ी बना। "ओणम सिर्फ़ एक त्योहार नहीं है। यह एकता का पाठ है। जब हम साथ हों, तो कोई भी बाधा हमें हरा नहीं सकती," वह युवाओं से हमेशा कहता था।', english: 'That Vallam Kali victory was talked about throughout all of Kerala. The news came: "A young boy participated in a great victory." Adithyan grew up. He became a renowned Vallam Kali champion. "Onam is not just a festival. It is a lesson in unity. When we are together, no obstacle can defeat us," he would say to young people.' },
    ],
    moral: 'Team spirit and unity can make even the smallest person achieve the greatest victories.',
    moralNative: 'टीम भावना और एकता सबसे छोटे व्यक्ति को भी सबसे बड़ी जीत दिला सकती है।',
  },

  // 14
  {
    title: 'The Magic Flute of the Western Ghats',
    titleNative: 'पश्चिमी घाट की जादुई बाँसुरी',
    category: 'Arts & Music 🎶',
    emoji: '🎶',
    paragraphs: [
      { native: 'कहा जाता है कि पश्चिमी घाट के पहाड़ों में एक जादुई बाँसुरी की धुन प्रकृति के साथ गूँजती है। जब पहाड़ों के बीच से हवा गुज़रती है, तो एक मधुर संगीत सुनाई देता है। उसे सुनकर मन शांत और स्थिर हो जाता है। उस संगीत को सुनने के लिए हज़ारों लोग उन पहाड़ों पर आते हैं। "यह कृष्ण की बाँसुरी की आवाज़ है," बुज़ुर्ग कहा करते थे।', english: 'It is said that in the Western Ghats mountains, a magical flute sound resonates in harmony with nature. When the wind comes between the mountains, a soft music is heard. When heard, the mind becomes peaceful and calm. Thousands of people come to those mountains just to hear that music. "This is the sound of Krishna\'s flute," the elders would say.' },
      { native: 'उन पहाड़ों की तलहटी में एक छोटी लड़की रहती थी। उसका नाम मीरा था। मीरा एक बेहद गरीब परिवार में पैदा हुई थी। पर उसके पास एक खास हुनर था — संगीत। जब वह गाती, तो पक्षी भी रुककर सुनने लगते। पहाड़ों की हवा उसके साथ मिलकर गूँजने लगती। पर किसी ने भी उसकी प्रतिभा को नहीं पहचाना। "एक गरीब लड़की को संगीत से क्या लेना-देना?" लोग कहते थे।', english: 'At the foothills of those mountains there lived a little girl. Her name was Meera. Meera was born in a very poor family. But she had one special talent — music. When she sang, the birds would stop and listen. The mountain wind would resonate in harmony with her. But no one recognized her talent. "What does music matter to a poor girl?" they would say.' },
      { native: 'एक दिन एक संगीत गुरु उसी पहाड़ी रास्ते से गुज़र रहे थे। उन्होंने मीरा का गीत सुना। वे रुक गए। उन्होंने आँखें बंद कर लीं। "यह आवाज़! यह पवित्रता! यह तो प्रकृति का अपना उपहार है!" उन्होंने सोचा। वे उस जगह पहुँचे जहाँ मीरा थी। एक गरीब झोंपड़ी में एक छोटी लड़की गीत गा रही थी।', english: 'One day a music guru was traveling along that mountain path. He heard Meera\'s song. He stopped walking. He closed his eyes. "This voice! This purity! This is nature\'s own gift!" he thought. He came to where Meera was. In a poor hut, a little girl was singing.' },
      { native: '"बच्ची, तुमने गाना किससे सीखा?" गुरु ने पूछा। मीरा ने कहा: "मैंने किसी से नहीं सीखा। मैंने हवा से सीखा। बारिश से सीखा। पहाड़ों से सीखा।" गुरु चकित रह गए। "तुम संगीत की बेटी हो। मैं तुम्हें प्रशिक्षित करूँगा," उन्होंने कहा। मीरा की आँखें खुशी से चमक उठीं।', english: '"Child, from whom did you learn to sing like this?" the guru asked. Meera said: "I did not learn from anyone. I learned from the wind. I learned from the rain. I learned from the mountains." The guru was astonished. "You are the daughter of music. I will train you," he said. Meera\'s eyes shone with joy.' },
      { native: 'मीरा ने गुरु से संगीत सीखा। उसने बड़ी मेहनत से अभ्यास किया। एक साल के भीतर वह एक अद्भुत संगीतकार बन गई। जब वह गाती, तो लगता जैसे पहाड़ थरथरा उठे हों। पूरा गाँव आकर सुनता। "मीरा के संगीत में प्रकृति की आवाज़ बसती है!" लोग कहते।', english: 'Meera learned music from the guru. She practiced very hard. Within one year she became a wonderful musician. When she sang, the mountains seemed to tremble. The whole village would come to listen. "In Meera\'s music, the sound of nature is present!" they would say.' },
      { native: 'मीरा ने एक बड़े संगीत समारोह में गाना गाया। हज़ारों लोग आए। उसने गाना शुरू किया। एक ही मिनट में पूरी भीड़ शांत हो गई। सबने ध्यान से सुना। आँखें बंद कर लीं। कुछ लोगों की आँखों से आँसू बह निकले। "यह संगीत हमें किसी और ही दुनिया में ले जाता है," लोगों ने कहा। जब मीरा ने गाना खत्म किया, तो तालियों की एक ज़बरदस्त गूँज उठी।', english: 'Meera sang at a grand music festival. Thousands of people came. She started to sing. Within a minute the crowd went still. Everyone listened. They closed their eyes. Some shed tears. "This music takes us to another world," they said. When Meera finished singing, a great round of applause arose.' },
      { native: 'जो लोग कभी कहते थे "एक गरीब लड़की को संगीत से क्या लेना-देना?" वही अब कहने लगे — "मीरा हमारे गाँव का गौरव है!" मीरा शांति से मुस्कुराई। "संगीत गरीब और अमीर दोनों के लिए एक समान है। यह प्रकृति की भाषा है। कोई भी इसे सीख सकता है। यह किसी को भी अपना बना सकता है," उसने कहा। पश्चिमी घाट के पहाड़ आज भी अपनी हवाओं में मीरा का नाम लिए गूँजते हैं।', english: '"What does music matter to a poor girl?" — those who once said this now said "Meera is the pride of our village!" Meera smiled quietly. "Music is the same for the poor and the rich. It is the language of nature. Anyone can learn it. Anyone can be possessed by it," she said. The Western Ghats mountains still carry the name of Meera in their winds and resonate with her memory even today.' },
    ],
    moral: 'True talent cannot be suppressed by poverty or circumstance. Nature recognizes its own.',
    moralNative: 'सच्ची प्रतिभा को गरीबी या परिस्थितियाँ दबा नहीं सकतीं। प्रकृति अपनों को खुद पहचान लेती है।',
  },

  // 15
  {
    title: 'The Golden Wheat Harvest',
    titleNative: 'सुनहरी गेहूँ की फसल',
    category: 'Village Fables 🌾',
    emoji: '🌾',
    paragraphs: [
      { native: 'उत्तर भारत के एक विशाल मैदान में एक गाँव था। उस गाँव का नाम सोनापुर था। उस गाँव में सब लोग गेहूँ की खेती करते थे। बैसाखी के त्योहार पर फसल का उत्सव मनाया जाता था। उस दिन सब लोग गाते थे। नाचते थे। गेहूँ से बने पकवान बनाकर खाते थे।', english: 'In a vast plain in North India there was a village. The name of that village was Sonapur. In that village everyone cultivated wheat. On the Vaisakhi festival the harvest celebration would take place. On that festival day everyone would sing. They would dance. They would cook and eat wheat dishes.' },
      { native: 'उस गाँव में दो पड़ोसी परिवार रहते थे। पहला परिवार अमर सिंह का था। दूसरा परिवार रवींद्र का था। दोनों परिवार गेहूँ की खेती करते थे। पर उनके बीच एक झगड़ा चल रहा था। वह झगड़ा ज़मीन की सीमा को लेकर था। "तुम्हारी ज़मीन मेरी ज़मीन में एक फुट घुस आई है," अमर सिंह कहता। "नहीं! तुम्हारी ज़मीन ही घुस आई है!" रवींद्र कहता।', english: 'In that village two neighboring families lived. The first family was Amar Singh\'s family. The second was Ravinder\'s family. Both families cultivated wheat. But between them there was a dispute. That dispute was about the boundary of their land. "Your land has come one foot into my land," said Amar Singh. "No! It is your land that has come into mine!" said Ravinder.' },
      { native: 'यह झगड़ा सालों तक चलता रहा। बच्चे भी आपस में लड़ते थे। बैसाखी के त्योहार पर भी वे साथ मिलकर उत्सव नहीं मनाते थे। गाँव दो हिस्सों में बँट गया। लोग दुखी होते। "एक फुट ज़मीन के लिए ये अपनी ज़िंदगी बर्बाद कर रहे हैं," वे आपस में कहते।', english: 'This dispute went on for years. Even the children quarreled. Even during the Vaisakhi festival they did not celebrate together. The village split into two. The people were saddened. "For one foot of land they are ruining their lives," they talked among themselves.' },
      { native: 'एक साल बारिश नहीं हुई। दोनों परिवार परेशान हो गए। गेहूँ की फसल मुरझा गई। फसल बहुत कम हुई। दोनों परिवार मुश्किल में थे। एक दिन अमर सिंह का बच्चा बीमार पड़ गया। दवा चाहिए थी। पैसे नहीं थे। अमर सिंह को समझ नहीं आ रहा था कि किससे मदद माँगे।', english: 'One year the rains failed. Both families were affected. The wheat crop withered. The harvest was poor. Both families were in great difficulty. One day Amar Singh\'s child fell ill. Medicine was needed. There was no money. Amar Singh did not know whom to ask for help.' },
      { native: 'रवींद्र ने यह खबर सुनी। वह हिचकिचाया। "यह मेरा दुश्मन है। पर बच्चा बीमार है।" उसकी अंतरात्मा ने उसे झकझोरा। रवींद्र ने अपने पास बचा हुआ आखिरी पैसा उठाया। वह अमर सिंह के घर गया। "बच्चे के लिए दवा खरीद लो। पैसे वापस करने की ज़रूरत नहीं है," उसने कहा।', english: 'Ravinder heard that news. He hesitated. "This man is my enemy. But the child is ill." His conscience spoke to him. Ravinder took the last money he had. He went to Amar Singh\'s house. "Buy medicine for the child. You do not need to return the money," he said.' },
      { native: 'अमर सिंह चकित रह गया। उसकी आँखों में आँसू आ गए। "सालों से मैं तुम्हें अपना दुश्मन मानता रहा। पर तुमने मेरे बच्चे की जान बचाई," उसने कहा। रवींद्र ने कहा: "ज़मीन की सीमा का जो भी हो। पर एक बच्चे की जान ज़्यादा ज़रूरी है।" उस दिन दोनों परिवार एक हो गए।', english: 'Amar Singh was astonished. Tears came to his eyes. "For years I thought of you as an enemy. But you saved my child," he said. Ravinder said: "Whatever happens about the land boundary. A child\'s life is more important." That day the two families came together.' },
      { native: 'अगले बैसाखी के त्योहार पर दोनों परिवारों ने साथ मिलकर उत्सव मनाया। उन्होंने ज़मीन की सीमा का झगड़ा भुला दिया। "गेहूँ के खेत में एक फुट ज़मीन, सालों की दोस्ती के आगे कुछ भी नहीं है। दोस्ती ही हमारी असली सुनहरी फसल है," दोनों परिवारों ने कहा। वह गाँव फिर से एक हो गया।', english: 'The next Vaisakhi festival, both families celebrated together. They forgot the land boundary dispute. "One foot of land in a wheat field is worth less than years of friendship. Friendship is our golden harvest," both families said. That village became one again.' },
    ],
    moral: 'Human bonds of love and kindness are more valuable than any piece of land or property.',
    moralNative: 'प्रेम और दया के मानवीय रिश्ते किसी भी ज़मीन या संपत्ति से कहीं ज़्यादा मूल्यवान होते हैं।',
  },,

  // 16
  {
    title: 'Akbar and Birbal\'s Khichdi',
    titleNative: 'अकबर और बीरबल की खिचड़ी',
    category: 'Kings & Scholars 🏰',
    emoji: '🍲',
    paragraphs: [
      { native: 'सर्दियों के मौसम में बादशाह अकबर और बीरबल यमुना नदी के तट पर टहल रहे थे। पानी बहुत ठंडा था। अकबर ने कहा: "क्या कोई इंसान इस ठंडे पानी में रात भर खड़ा रह सकता है?" एक गरीब ब्राह्मण ने यह चुनौती स्वीकार की।', english: 'In winter season Emperor Akbar and Birbal were walking on the banks of Yamuna. The water was very cold. Akbar said: "Can any human stand in this cold water all night?" A poor Brahmin accepted this challenge.' },
      { native: 'ब्राह्मण रात भर ठंडे पानी में खड़ा रहा। सुबह अकबर ने पूछा: "तुम इतनी ठंड में कैसे खड़े रहे?" ब्राह्मण ने कहा: "महाराज, दूर महल के एक दीये की रोशनी को देखकर मुझे गर्मी और ढांढस मिलता रहा।" अकबर ने इनाम देने से मना कर दिया।', english: 'The Brahmin stood in cold water all night. In the morning Akbar asked: "How did you stand in such cold?" The Brahmin said: "Maharaj, looking at a lamp\'s light in the distant palace gave me warmth and comfort." Akbar refused to give the reward.' },
      { native: 'अगले दिन बीरबल दरबार नहीं आए। अकबर उनके घर गए। बीरबल जमीन पर आग जलाकर बहुत ऊपर एक मटकी में खिचड़ी पका रहे थे। अकबर ने कहा: "बीरबल, इतनी दूर आग से खिचड़ी कैसे पकेगी?"', english: 'The next day Birbal did not come to court. Akbar went to his house. Birbal lit a fire on the ground and was cooking khichdi in a pot hung high above. Akbar said: "Birbal, how will khichdi cook from a fire so far?"' },
      { native: 'बीरबल ने मुस्कुराकर कहा: "जहांपनाह, जब दूर महल के दीये से ब्राह्मण को गर्मी मिल सकती है, तो इस आग से मेरी खिचड़ी क्यों नहीं पक सकती?" अकबर अपनी गलती समझ गए।', english: 'Birbal smiled and said: "Emperor, when a Brahmin can get warmth from a distant palace lamp, why can\'t my khichdi cook from this fire?" Akbar realized his mistake.' },
      { native: 'अकबर ने ब्राह्मण को दरबार में बुलवाकर पूरा इनाम दिया। बीरबल की बुद्धिमानी ने एक निर्दोष गरीब की मदद की।', english: 'Akbar called the Brahmin to court and gave the full reward. Birbal\'s wisdom helped an innocent poor man.' },
    ],
    moral: 'Clever wit used in defense of justice can right any wrong.',
    moralNative: 'न्याय के पक्ष में उपयोग की गई बुद्धिमत्ता किसी भी अन्याय को ठीक कर सकती है।',
  },

  // 17
  {
    title: 'The Story of Holi and Prahlad',
    titleNative: 'होली और भक्त प्रह्लाद की कथा',
    category: 'Festivals & Traditions 🪔',
    emoji: '🎨',
    paragraphs: [
      { native: 'प्राचीन काल में हिरण्यकश्यप नाम का एक अहंकारी राजा था। वह चाहता था कि सब उसी की पूजा करें। लेकिन उसका पुत्र प्रह्लाद भगवान विष्णु का परम भक्त था।', english: 'In ancient times there was an arrogant king named Hiranyakashipu. He wanted everyone to worship him. But his son Prahlad was a supreme devotee of Lord Vishnu.' },
      { native: 'राजा ने प्रह्लाद को मारने की बहुत कोशिश की, लेकिन हर बार विष्णु जी ने प्रह्लाद की रक्षा की। राजा की बहन होलिका को वरदान था कि वह आग से नहीं जलेगी।', english: 'The king tried hard to kill Prahlad, but every time Lord Vishnu protected him. The king\'s sister Holika had a boon that fire would not burn her.' },
      { native: 'होलिका प्रह्लाद को गोद में लेकर चिता पर बैठ गई। लेकिन भगवान की कृपा से होलिका जलकर राख हो गई और प्रह्लाद हंसते हुए सुरक्षित बाहर आ गए।', english: 'Holika sat on a pyre holding Prahlad in her lap. But by God\'s grace Holika burned to ashes and Prahlad came out safely smiling.' },
      { native: 'तभी से बुराई पर अच्छाई की जीत के रूप में होलिका दहन और रंगों का त्योहार होली मनाया जाता है। लोग आपस में प्यार से रंग लगाते हैं।', english: 'Since then Holika Dahan and the festival of colors Holi are celebrated as triumph of good over evil. People lovingly apply colors to each other.' },
      { native: 'सच्ची भक्ति और सच्चाई की हमेशा जीत होती है, चाहे कितनी भी बड़ी शक्ति सामने हो।', english: 'True devotion and truth always triumph, no matter how great the opposing force.' },
    ],
    moral: 'Truth and devotion will always triumph over pride and evil.',
    moralNative: 'सत्य और भक्ति की हमेशा अहंकार और बुराई पर विजय होती है।',
  },

  // 18
  {
    title: 'The Potter and the Magic Diya',
    titleNative: 'कुम्हार और जादुई दीया',
    category: 'Village Fables 🌾',
    emoji: '🪔',
    paragraphs: [
      { native: 'गंगा तट के पास एक गांव में रामू नाम का एक कुम्हार रहता था। वह दिन-रात मिट्टी के बर्तन और दीये बनाता था। दिवाली से पहले वह बहुत मेहनत करता था।', english: 'In a village near the Ganges lived a potter named Ramu. He made clay pots and diyas day and night. Before Diwali he worked very hard.' },
      { native: 'एक दिन एक बूढ़े साधु ने उससे दीया मांगा। रामू ने अपना सबसे सुंदर दीया साधु को दे दिया और पैसे लेने से इनकार कर दिया।', english: 'One day an old saint asked him for a diya. Ramu gave his most beautiful diya to the saint and refused to take money.' },
      { native: 'साधु ने आशीर्वाद दिया: "रामू, तुम्हारी इस निस्वार्थ सेवा से तुम्हारे बनाए हर दीये में शांति और समृद्धि की रोशनी चमकेगी।"', english: 'The saint blessed: "Ramu, through your selfless service, the light of peace and prosperity will shine in every diya you make."' },
      { native: 'उस दिवाली रामू के सारे दीये बिक गए। जो लोग उसके दीये ले गए, उनके घरों में सुख और शांति छा गई।', english: 'That Diwali all of Ramu\'s diyas sold out. In the homes of people who bought his diyas, happiness and peace rained.' },
      { native: 'हाथ की मेहनत और साफ दिल से किया गया काम हमेशा समाज को खुशहाली देता है।', english: 'Work done with hard hands and a pure heart always brings prosperity to society.' },
    ],
    moral: 'Purity of intent turns honest labour into a blessing for everyone.',
    moralNative: 'इरादे की पवित्रता ईमानदार मेहनत को सभी के लिए आशीर्वाद बना देती है।',
  },

  // 19
  {
    title: 'The Sacred River Ganges',
    titleNative: 'पवित्र नदी गंगा की कथा',
    category: 'Mythology & Legends 🔱',
    emoji: '🌊',
    paragraphs: [
      { native: 'सूर्यवंशी राजा भगीरथ ने अपने पूर्वजों के उद्धार के लिए हजारों वर्षों तक कठिन तपस्या की। उनकी तपस्या से प्रसन्न होकर ब्रह्मा जी ने गंगा को धरती पर भेजने का वरदान दिया।', english: 'Surya dynasty king Bhagirath performed tough penance for thousands of years for salvation of his ancestors. Pleased with his penance Lord Brahma granted boon to send Ganges to Earth.' },
      { native: 'गंगा का वेग इतना तेज था कि धरती उसे सहन नहीं कर सकती थी। भगीरथ ने भगवान शिव की प्रार्थना की। शिव जी ने गंगा को अपनी जटाओं में रोक लिया।', english: 'Ganges\' force was so strong that Earth could not bear it. Bhagirath prayed to Lord Shiva. Shiva contained Ganges in his matted locks.' },
      { native: 'शिव जी ने गंगा की शांत धारा को धरती पर बहने दिया। गंगा जी भगीरथ के पीछे-पीछे चलीं और उनके पूर्वजों का उद्धार किया।', english: 'Shiva released gentle streams of Ganges onto Earth. Ganges followed Bhagirath and liberated his ancestors.' },
      { native: 'आज भी गंगा नदी लाखों लोगों के जीवन और खेती का आधार है। भारतीय संस्कृति में गंगा को मां का दर्जा दिया गया है।', english: 'Even today Ganges river is the sustenance of life and farming for millions. In Indian culture Ganges is revered as a mother.' },
      { native: 'अथक प्रयास और समर्पण से असंभव काम भी संभव हो जाता है।', english: 'With tireless effort and dedication even impossible tasks become possible.' },
    ],
    moral: 'Unwavering determination and devotion can bring heavenly grace down to solve earthly troubles.',
    moralNative: 'अडिग संकल्प और भक्ति सांसारिक कष्टों को दूर करने के लिए दिव्य कृपा ला सकती है।',
  },

  // 20
  {
    title: 'The Charkha and Self-Reliance',
    titleNative: 'चरखा और स्वावलंबन',
    category: 'Morals & Wisdom 🌟',
    emoji: '🧵',
    paragraphs: [
      { native: 'साबरमती आश्रम में महात्मा गांधी रोज सुबह चरखा चलाते थे। एक दिन एक नवयुवक ने पूछा: "बापू, चरखा चलाने से आजादी कैसे मिलेगी?"', english: 'In Sabarmati Ashram Mahatma Gandhi spun the charkha every morning. One day a youth asked: "Bapu, how will spinning charkha bring freedom?"' },
      { native: 'गांधी जी ने मुस्कुराकर उत्तर दिया: "चरखा केवल सूत नहीं कातता, यह हमें स्वावलंबी बनाता है। जब हम अपने कपड़े खुद बनाएंगे, तो हम किसी के गुलाम नहीं रहेंगे।', english: 'Gandhi smilingly replied: "The charkha does not just spin yarn, it makes us self-reliant. When we make our own clothes we remain slaves to no one.' },
      { native: 'हर एक धागा हमारे देशवासियों की एकता और श्रम का प्रतीक है। आत्मनिर्भरता ही सच्ची स्वतंत्रता का आधार है।"', english: 'Every single thread is a symbol of unity and labor of our countrymen. Self-reliance is the foundation of true freedom."' },
      { native: 'उस युवक ने भी चरखा चलाना सीखा। खादी भारत के स्वतंत्रता संग्राम की सबसे बड़ी पहचान बन गई।', english: 'That youth also learned to spin the charkha. Khadi became the greatest identity of India\'s freedom struggle.' },
      { native: 'अपनी मेहनत पर भरोसा करना और आत्मनिर्भर बनना ही जीवन की सबसे बड़ी ताकत है।', english: 'Relying on one\'s own hard work and becoming self-reliant is the greatest strength of life.' },
    ],
    moral: 'Self-reliance and dignity of labour are the true foundations of freedom and self-respect.',
    moralNative: 'स्वावलंबन और श्रम की प्रतिष्ठा ही स्वतंत्रता और आत्मसम्मान की सच्ची नींव है।',
  },
];
